---
- name: Create dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ confd }}"
    - "{{ defaultd }}"
    - "{{ included }}"

- name: Copy configs
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  loop:
    - src: 10-ssl-cache.conf
      dest: "{{ confd }}"
    - src: 10-gzip.conf
      dest: "{{ defaultd }}"
  notify: validate nginx

- name: Remove obsolete configs
  file:
    path: "{{ item.path }}"
    state: absent
  loop:
    - path: /etc/nginx/default.d/12-body.conf
  notify: validate nginx

- name: Template configs
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ item.dest }}/{{ item.src }}"
    mode: 0644
  loop:
    - src: 00-dummy.conf
      dest: "{{ confd }}"
    - src: allow_status.conf
      dest: "{{ included }}"
  notify: validate nginx
...
