---
- name: Yum section
  block:
    - name: yum install nginx
      yum:
        name: "{{ nginx_packages }}"

    - name: yum package awstats
      yum:
        name: awstats
        state: "{{ awstats_enable|d()|ternary('present','absent') }}"
  when: "ansible_pkg_mgr == 'yum'"

- name: dnf install nginx
  dnf:
    name: "{{ nginx_packages }}"
  when: "ansible_pkg_mgr == 'dnf'"
...
