---
- name: "Template 91-awstats.j2"
  template:
    dest: "{{ confd }}/91-awstats.conf"
    src: 91-awstats.j2
    owner: root
    mode: 0644
    force: no
  when: awstats_enable|d()
  tags: [awstats]
...
