---
- name: Check if role assigned to host
  fail:
    msg: "Role 'httpd' is not assigned to this host"
  when: "'httpd' not in roles"

- import_tasks: packages.yml

- name: "Set Listen directive"
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    regexp: '^Listen *'
    line: "Listen 127.0.0.1:{{ httpd_port |d('8888') }}"
  tags: [conf]
  notify: config restart httpd

# MODULES
- name: "Enable MPM-ITK"
  lineinfile:
    dest: "/etc/httpd/conf.modules.d/00-mpm-itk.conf"
    backrefs: yes
    regexp: '^.*LoadModule(\s+)mpm_(.*)$'
    line: 'LoadModule\1mpm_\2'
  when:  ansible_distribution == "CentOS" and ansible_distribution_major_version|int >= 7
  tags: [conf]

# UMASK
- name: "Set umask for httpd service (sysconfig)"
  lineinfile:
    dest: "/etc/sysconfig/httpd"
    line: 'umask 002'
  notify: config restart httpd
  tags: [services]

# - name: "Set umask for httpd service (systemd)"
#   blockinfile:
#     dest: /etc/systemd/system/httpd.service.d/httpd.conf
#     create: yes
#     marker: "# {mark} ANSIBLE MANAGED BLOCK: UMASK"
#     block: |
#       [Service]
#       UMask=0002
#   notify: config reload systemd
#   tags: [services]

- import_tasks: logrotate.yml

- include_tasks: awstats.yml
...
