---
- name: Check if role assigned to host
  fail:
    msg: "Role 'httpd' is not assigned to this host"
  when: "'httpd' not in roles"

- name: "Check required parameter"
  fail:
    msg: "Please add PHP version parameter (-e remi_php_version=56|70|71)"
  when: remi_php_version is not defined
  tags: [remi]

- include: packages.yml

- include: selinux.yml

# CONFIGURATION
- name: "Copy TEMPLATE_NG_A2(_SSL)"
  copy:
    dest: "{{ confd }}"
    src: "{{ item }}"
    force: yes
  with_items:
    - TEMPLATE_NG_A2
    - TEMPLATE_NG_A2_SSL
  tags: [conf,templates]

- name: "Copy TEMPLATE_A2"
  copy:
    dest: "{{ a2d }}"
    src: TEMPLATE_A2
    force: yes
  tags: [conf,templates]

- name: "Set Listen directive"
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    regexp: '^Listen *'
    line: 'Listen 127.0.0.1:8888'
  tags: [conf]
  notify: config restart httpd

# MODULES
- name: "Enable MPM-ITK"
  lineinfile:
    dest: "/etc/httpd/conf.modules.d/00-mpm-itk.conf"
    backrefs: yes
    regexp: '^.*LoadModule(\s+)mpm_(.*)$'
    line: 'LoadModule\1mpm_\2'
  when:  ansible_distribution == "CentOS" and ansible_distribution_major_version|int >= 7
  tags: [conf]

# PHP TIMEZONE
- stat: path=/etc/php.ini
  register: php_ini
  tags: [ php ]

- name: "Set timezone in php.ini [rh-based]"
  lineinfile:
    dest: "/etc/php.ini"
    regexp: '(^date.timezone\s*=\s*(?!{{ timezone|default(''Europe/Moscow'') }})|;date.timezone\s*=\s*)'
    line: 'date.timezone = {{ timezone|default(''Europe/Moscow'') }}'
  when: php_ini.stat.exists
  tags: [ php, timezone ]

# UMASK
- name: "Set umask for httpd service (sysconfig)"
  lineinfile:
    dest: "/etc/sysconfig/httpd"
    line: 'umask 002'
  notify: config restart httpd
  tags: [services]

# - name: "Set umask for httpd service (systemd)"
#   blockinfile:
#     dest: /etc/systemd/system/httpd.service.d/httpd.conf
#     create: yes
#     marker: "# {mark} ANSIBLE MANAGED BLOCK: UMASK"
#     block: |
#       [Service]
#       UMask=0002
#   notify: config reload systemd
#   tags: [services]

- include: logrotate.yml

- include: awstats.yml
...
