---
- name: Check if role assigned to host
  assert:
    that:
      - "'httpd' in server_roles"
    msg: "Role 'httpd' is not assigned to this host"

- import_tasks: packages.yml

- name: "Comment Listen directives"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^(Listen\s+[.:0-9])$'
    line: "# \1"
    backrefs: yes
  tags: [ conf ]
  notify: config validate httpd restart

- name: Insert LISTEN block
  blockinfile:
    path: /etc/httpd/conf/httpd.conf
    insertafter: "# Listen"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: LISTEN"
    block: |
      Listen 127.0.0.1:{{ httpd_port|d('8888') }} # MARK
      {% for item in httpd_listen_add %}
      Listen {{ item.addr }}:{{ item.port }} #MARK
      {% enfor %}
  tags: [ conf ]
  notify: config validate httpd restart

# MODULES
- name: "Enable MPM-ITK"
  lineinfile:
    dest: "/etc/httpd/conf.modules.d/00-mpm-itk.conf"
    backrefs: yes
    regexp: '^.*LoadModule(\s+)mpm_(.*)$'
    line: 'LoadModule\1mpm_\2'
  when:  ansible_distribution == "CentOS" and ansible_distribution_major_version|int >= 7
  tags: [ conf ]

# UMASK
- name: "Set umask for httpd service (sysconfig)"
  lineinfile:
    dest: "/etc/sysconfig/httpd"
    line: 'umask 002'
  notify: config validate httpd restart
  tags: [ services ]

- import_tasks: logrotate.yml

- include_tasks: awstats.yml
...
