---
- name: Section 7
  block:
    - name: Setup southbridge repo
      yum_repository:
        name: southbridge-stable
        description: Southbridge stable packages repository
        baseurl: http://rpms.southbridge.ru/rhel{{ ansible_distribution_major_version }}/stable/$basearch/
        gpgcheck: yes
        gpgkey: http://rpms.southbridge.ru/RPM-GPG-KEY-southbridge
        enabled: no
        priority: "10"

    - name: Yum install pyOpenSSL
      yum:
        enablerepo: southbridge-stable
        name: python2-pyOpenSSL-16.2.0
  when:
    - ansible_distribution_file_variety == "RedHat"
    - ansible_distribution_major_version|int == 7
...
