---
- name: dummy
  command: "true"

#####
# HOSTNAME
#
- name: hostname 6
  shell: "hostname {{ ansible_fqdn }}"

#####
# SELinux
#
- name: touch autorelabel
  file:
    path: "/.autorelabel"
    state: touch

- name: restorecon common_sh_mon
  command: restorecon -R /usr/local/bin
  when: selinux_state != "disabled"

#####
# xt_recent
#
- name: xt_recent stop iptables
  service: name=iptables state=stopped
  notify: xt_recent remove module

- name: xt_recent remove module
  modprobe: name=xt_recent state=absent
  notify: xt_recent insert module

- name: xt_recent insert module
  modprobe: name=xt_recent state=present params="ip_list_tot=6000 ip_pkt_list_tot=255"
  notify: xt_recent start iptables

- name: xt_recent start iptables
  service: name=iptables state=started

#####
# IPTables restart
#
- name: config restart iptables
  service: name=iptables state=restarted

#####
# Journald restart
#
- name: config restart journald
  systemd:
    name: "systemd-journald.service"
    state: restarted

- name: config journal-gateway enable
  systemd:
    name: "systemd-journal-gatewayd.socket"
    state: started
    enabled: yes

#####
# NTPd restart
#
- name: config restart ntpd
  service: name=ntpd state=restarted

- name: config restart crond
  service: name=crond state=restarted

- name: config reload crond
  service: name=crond state=reloaded
  when: ansible_distribution_file_variety == 'RedHat'

- name: config reload cron
  service: name=cron state=reloaded
  when: ansible_distribution_file_variety == 'Debian'

#####
# SNMPd restart
#
- name: config restart snmpd
  service: name=snmpd state=restarted

#####
# Icinga2 reload
#
- name: config reload icinga2
  systemd:
    name: "icinga2.service"
    state: reloaded
  delegate_to: "{{ common_icinga2_master }}"

#####
# newaliases
#
- name: config newaliases
  command: newaliases

#####
# tuned
- name: config tuned
  service: name=tuned enabled=yes state=started
  notify: tuned profile

- name: tuned profile
  command: tuned-adm profile virtual-guest
  when: ansible_virtualization_role == "guest"

#####
# SSHd disable root login
- name: disable root ssh login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#{,1}\s*PermitRootLogin\s+.*$'
    line: 'PermitRootLogin no'
    # notify: service sshd reload

- name: service sshd reload
  service: name=sshd state=reloaded

####
# Sysctl
- name: config set sysctl
  command: >
    sysctl -p {{ common_sysctl_file }}

####
# Sosnole
- name: initctl
  command: "initctl start ttyS0"

- name: systemd ttyS0 restart
  systemd:
    daemon_reload: yes
    name: getty@ttyS0.service
    state: restarted

- name: systemd tty1 restart
  systemd:
    daemon_reload: yes
    name: getty@tty1.service
    state: restarted

####
# Etckeeper
- name: etckeeper commit
  command: 'etckeeper commit "ansible common role installed"'

...
