---
#####
# HOSTNAME
#
- name: hostname 6
  shell: "hostname {{ ansible_fqdn }}"

#####
# Porntubeuploader
#
- name: restorecon ptr_se
  command: restorecon -R /usr/local/bin
  notify: copy ptr_se
  when: selinux_state != "disabled"

- name: copy ptr_se
  copy: src={{ ptr_se }}.te dest=/var/local/{{ ptr_se }}.te
  notify: checkmodule ptr_se

- name: checkmodule ptr_se
  command: checkmodule -M -m -o /var/local/{{ ptr_se }}.mod /var/local/{{ ptr_se }}.te
  notify: package ptr_se

- name: package ptr_se
  command: semodule_package -o /var/local/{{ ptr_se }}.pp -m /var/local/{{ ptr_se }}.mod
  notify: install ptr_se

- name: install ptr_se
  command: semodule -i /var/local/{{ ptr_se }}.pp
  notify: rm ptr_se

- name: rm ptr_se
  file:
    path: /var/local/{{ ptr_se }}.{{ item }}
    state: absent
  with_items:
    - te
    - mod
    - pp

#####
# xt_recent
#
- name: xt_recent stop iptables
  service: name=iptables state=stopped
  notify: xt_recent remove module

- name: xt_recent remove module
  modprobe: name=xt_recent state=absent
  notify: xt_recent insert module

- name: xt_recent insert module
  modprobe: name=xt_recent state=present params="ip_list_tot=6000 ip_pkt_list_tot=255"
  notify: xt_recent start iptables

- name: xt_recent start iptables
  service: name=iptables state=started

#####
# IPTables restart
#
- name: config restart iptables
  service: name=iptables state=restarted

#####
# Journald restart
#
- name: config restart journald
  service: name=systemd-journald state=restarted

#####
# NTPd restart
#
- name: config restart ntpd
  service: name=ntpd state=restarted

#####
# SNMPd restart
#
- name: config restart snmpd
  service: name=snmpd state=restarted

#####
# Icinga2 reload
#
- name: config reload icinga2
  systemd:
    name: "icinga2.service"
    state: reloaded
  delegate_to: "{{ common_icinga2_master }}"

#####
# newaliases
#
- name: config newaliases
  command: newaliases

#####
# tuned
- name: config tuned
  service: name=tuned enabled=yes state=started
  notify: tuned profile

- name: tuned profile
  command: tuned-adm profile virtual-guest
  when: ansible_virtualization_role == "guest"

#####
# SSHd disable root login
- name: disable root ssh login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#{,1}\s*PermitRootLogin\s+.*$'
    line: 'PermitRootLogin no'
    # notify: service sshd reload

- name: service sshd reload
  service: name=sshd state=reloaded

####
# Sosnole
- name: initctl
  command: "initctl start ttyS0"

- name: systemd ttyS0 restart
  systemd:
    daemon_reload: yes
    name: getty@ttyS0.service
    state: restarted

- name: systemd tty1 restart
  systemd:
    daemon_reload: yes
    name: getty@tty1.service
    state: restarted

####
# Etckeeper
- name: etckeeper commit
  command: 'etckeeper commit "ansible common role installed"'

#####
# Reboot
- name: config reboot
  shell: shutdown -r +1
  ignore_errors: True
  async: 0
  poll: 0

...
