---
- name: Check role requirements
  assert:
    that:
      - inventory_hostname in groups['nodejs']
      - ansible_distribution_file_variety == "RedHat"
      - ansible_distribution_major_version|int >= 7

- name: Install nodejs repo
  yum:
    name: >
      https://rpm.nodesource.com/pub_{{ nodejs_major_version
      }}.x/el/{{ ansible_distribution_major_version }}/{{ ansible_architecture
      }}/nodesource-release-el{{ ansible_distribution_major_version }}-1.noarch.rpm

- name: Yum install nodejs
  yum:
    name: nodejs

- name: Yarn section
  block:
    - name: Ensure yarn repository key is present
      rpm_key:
        key: "https://dl.yarnpkg.com/rpm/pubkey.gpg"

    - name: Create yarn repo
      yum_repository:
        name: yarn
        description: Yarn Repository
        file: yarn
        baseurl: https://dl.yarnpkg.com/rpm/
        enabled: yes
        gpgcheck: yes
        gpgkey: https://dl.yarnpkg.com/rpm/pubkey.gpg

    - name: Yum install yarn
      yum:
        name: yarn
  when: nodejs_yarn_install|d()
...
