---
- name: config restart ipset
  service:
    name: ipset
    enabled: yes
    state: restarted
  tags: [iptables,ipset]

- name: config restart iptables
  service:
    name: iptables
    enabled: yes
    state: restarted
  tags: [iptables]

- name: config restart squid
  service:
    name: squid
    enabled: yes
    state: restarted
  tags: [squid]

