---
- hosts: all
  become: yes
  become_method: sudo

  tasks:
  - name: "Edit snmpd.conf"
    lineinfile:
      dest: "/etc/snmp/snmpd.conf"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      backrefs: yes
    with_items:
      - { regexp: '^(.*)-m sysfiles(.*)$', line: '\1-m passwd\2' }
      - { regexp: '^(.*)-m dmesg(.*)$', line: '\1-m conntrack -f\2' }
    notify:
        - restart snmpd

  handlers:
    - name: restart snmpd
      service: name=snmpd state=restarted

### EOF
