---
- name: "Copy awstats.pl.patch"
  copy:
    src: "awstats.pl.patch"
    dest: "/var/local/"
    force: no
  notify: awstats patch
  tags: [awstats]

- meta: flush_handlers

- name: "Copy awstatstotals.php"
  copy:
    src: "awstatstotals.php"
    dest: "/usr/share/awstats/wwwroot/cgi-bin/"
    owner: root
    mode: 0644
    force: no
  tags: [awstats]

- name: "Check if awstats.conf exists"
  stat: path=/etc/awstats/awstats.conf
  register: awstatsconf
  tags: [awstats]

- name: "Create symlink awstats.conf"
  shell: cd /etc/awstats && ln -s awstats.localhost.localdomain.conf awstats.conf
  ignore_errors: true
  when: awstatsconf.stat.exists == False
  tags: [awstats]

- name: "Copy awstats.TEMPLATE"
  copy:
    src: "awstats.TEMPLATE"
    dest: "/etc/awstats/"
    owner: root
    mode: 0644
    force: yes
  tags: [awstats,templates]
...
