---
- name: "Ensure default.d"
  file: path={{ defaultd }} state=directory mode=0755
  tags: [nginx]

- name: "Copy configs to default.d"
  copy: src={{ item }} dest={{ defaultd }} force=yes
  with_items:
    - 10-gzip.conf
    - 12-body.conf
  tags: [nginx]
...
