---
- name: "Ensure exists {{ html }}"
  file:
    path: "{{ html }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: [nginx]

- name: "Copy index.html to {{ html }}"
  copy: src={{ item }} dest={{ html }} force=yes
  with_items:
    - index.html
  tags: [nginx]
...
