---
- name: "Ensure exists {{ html }}"
  file:
    path: "{{ html }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: [nginx]

- name: "Copy index.html to {{ html }}"
  copy:
    src: "{{ item }}"
    dest: "{{ html }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - index.html
  tags: [nginx]
...
