---
- name: "Ensure include.d"
  file: path={{ included }} state=directory mode=0755
  tags: [nginx]

- name: "Copy configs to include.d"
  copy: src={{ item }} dest={{ included }} force=yes
  with_items:
    - proxy_common.conf
    - ssl_common.conf
  tags: [ nginx ]

- name: "Template config to include.d"
  template:
    src: "allow_status.conf.j2"
    dest: "{{ included }}/allow_status.conf"
    force: yes
  tags: [ nginx ]

- name: "Create listen.conf"
  lineinfile:
    dest: "{{ included }}/listen.conf"
    line: "listen {{ public_ip }}:80;"
    create: yes

- name: "Create listen_ssl.conf"
  lineinfile:
    dest: "{{ included }}/listen_ssl.conf"
    line: "listen {{ public_ip }}:443 ssl;"
    create: yes

- name: "Create listen_default.conf"
  lineinfile:
    dest: "{{ included }}/listen_default.conf"
    line: "listen {{ public_ip }}:80 default_server;"
    create: yes

- name: "Create listen_default_ssl.conf"
  lineinfile:
    dest: "{{ included }}/listen_default_ssl.conf"
    line: "listen {{ public_ip }}:443 default_server ssl;"
    create: yes

- name: "Create listen_inside.conf"
  blockinfile:
    dest: "{{ included }}/listen_inside.conf"
    block: |
      listen {{ private_ip }}:80;
    create: yes
...
