---
- name: "Ensure include.d"
  file: path={{ included }} state=directory mode=0755
  tags: [ nginx ]

- name: "Template config to include.d"
  template:
    src: "allow_status.conf.j2"
    dest: "{{ included }}/allow_status.conf"
    force: yes
  notify: config reload nginx
  tags: [ nginx, allow_status ]
...
