---
- name: Delete obsolete logrotate nginx_sites
  file:
    path: /etc/logrotate.d/nginx_sites
    state: absent
  tags: [ logrotate ]

- name: Create nginx-prerotate dir
  file:
    path: "/etc/logrotate.d/nginx-prerotate"
    state: directory
  when: awstats_enable|d()
  tags: [ awstats, logrotate ]

- name: "logrotate nginx site logs (prerotate)"
  copy:
    src: "awstats.prerotate"
    dest: "/etc/logrotate.d/nginx-prerotate/awstats"
    force: no
    owner: root
    group: root
    mode: 0754
  when: awstats_enable|d()
  tags: [ awstats, logrotate ]

- name: remove prerotate ansible config
  file:
    path: "/etc/logrotate.d/nginx-prerotate/awstats"
    state: absent
  when: not awstats_enable|d()
  tags: [ awstats, logrotate ]
...
