---
- import_tasks: packages.yml

- import_tasks: html.yml

- import_tasks: set_if.yml

- import_tasks: default.d.yml

- import_tasks: include.d.yml

- include_tasks: conf.d.yml
  tags: [ nginx, templates ]

- include_tasks: tls.yml
  when: not alien
  tags: [ tls ]

- name: Copy nginx.conf
  copy:
    backup: yes
    dest: "/etc/nginx/nginx.conf"
    force: yes
    src: "nginx.conf"
    validate: 'nginx -tc %s'
  notify: config restart nginx
  tags: [nginx]

- import_tasks: iptables.yml

- import_tasks: logrotate.yml

- import_tasks: awstats.yml

- name: "Copy scripts"
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/"
    owner: root
    group: root
    mode: 0755
    force: yes
  with_items:
    - "vhostinit.sh"
    - "dbinit.sh"
  tags: [scripts]

- name: "Create symlinks in /usr/bin/"
  file:
    src: "/usr/local/bin/{{ item }}.sh"
    dest: "/usr/bin/{{ item }}"
    state: link
    force: no
  with_items:
    - "vhostinit"
    - "dbinit"
  tags: [scripts]
...
