---
- name: Check if role assigned to host
  fail:
    msg: "ROLE 'nginx' IS NOT ASSIGNED TO THIS HOST"
  when: "'nginx' not in roles"

- import_tasks: packages.yml

- import_tasks: html.yml

- import_tasks: default.d.yml

- import_tasks: include.d.yml

- include_tasks: conf.d.yml
  tags: [ nginx, templates ]

- include_tasks: tls.yml
  when: not alien
  tags: [ tls ]

- name: Copy nginx.conf
  copy:
    backup: yes
    dest: "/etc/nginx/nginx.conf"
    force: yes
    src: "nginx.conf"
    validate: 'nginx -tc %s'
  notify: config restart nginx
  tags: [nginx]

- import_tasks: iptables.yml

- import_tasks: logrotate.yml

- import_tasks: awstats.yml
...
