---
- name: Check if role assigned to host
  fail:
    msg: "ROLE 'nginx' IS NOT ASSIGNED TO THIS HOST"
  when: "'nginx' not in roles"

- name: Import packages
  import_tasks: packages.yml

- name: Import html
  import_tasks: html.yml

- name: Import default.d
  import_tasks: default.d.yml

- name: Import include.d
  import_tasks: include.d.yml

- name: Import conf.d
  import_tasks: conf.d.yml

- name: Import TLS tasks
  import_tasks: tls.yml

- name: Template nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    validate: 'nginx -tc %s'
    backup: yes
  notify: config restart nginx
  tags: [ nginx ]

- name: Include iptables
  include_tasks: iptables.yml
  when: ansible_distribution_major_version|int <= 7

- name: Import sysctl
  import_tasks: sysctl.yml
  when: ansible_virtualization_type != 'openvz'

- name: Import logrotate
  import_tasks: logrotate.yml

- name: Import awstats
  import_tasks: awstats.yml
...
