---
- name: yum install nginx
  yum:
    name: "{{ nginx_packages }}"
    state: present
  when: ansible_distribution_major_version|int <= 7
  tags: [ packages ]

- name: yum package awstats
  yum:
    name: awstats
    state: "{{ awstats_enable|d()|ternary('present','absent') }}"
  when: ansible_distribution_major_version|int <= 7
  tags: [ packages ]

- name: dnf install nginx
  dnf:
    name: "{{ nginx_packages }}"
    state: present
  when: ansible_distribution_major_version|int > 7
  tags: [ packages ]
...
