---
- name: "Install Nginx (YUM)"
  yum:
    state: present
    name: "{{ item }}"
  with_items:
    - '{{ nginx_packages }}'
  when: ansible_distribution == "CentOS"
  tags: [packages]

- name: "Install Nginx (DNF)"
  dnf:
    state: present
    name: "{{ item }}"
  with_items:
    - '{{ nginx_packages }}'
  when: ansible_distribution == "Fedora"
  tags: [packages]
...
