---
- name: "Install Nginx (YUM)"
  yum:
    name: "{{ nginx_packages }}"
    state: present
  when: ansible_distribution == "CentOS"
  tags: [ packages ]

- name: "Install Nginx (DNF)"
  dnf:
    name: "{{ nginx_packages }}"
    state: present
  when: ansible_distribution == "Fedora"
  tags: [ packages ]
...
