---
- name: Generate privkey for self-signed cert
  openssl_privatekey:
    path: "{{ nginx_self_signed.key }}"
  notify: validate nginx

- name: Generate CSR for self-signed cert
  openssl_csr:
    path: "{{ nginx_self_signed.csr }}"
    privatekey_path: "{{ nginx_self_signed.key }}"
    common_name: "{{ ansible_fqdn }}"
    country_name: RU
    organization_name: "{{ nginx_self_signed_csr.org }}"
    email_address: "{{ nginx_self_signed_csr.email }}"
  notify: validate nginx

- name: Generate self-signed cert
  openssl_certificate:
    path: "{{ nginx_self_signed.cert }}"
    privatekey_path: "{{ nginx_self_signed.key }}"
    csr_path: "{{ nginx_self_signed.csr }}"
    provider: selfsigned
  notify: validate nginx
...
