---
- name: Check if role assigned to host
  assert:
    that:
      - inventory_hostname in groups['ftpd']
      - ansible_distribution_major_version|int >= 7

- import_tasks: "packages.yml"
  tags: [ packages ]

- include_tasks: "{{ ftpd_variety }}.yml"
...
