---
- name: touch zshrc
  file:
    path: "/home/{{ username }}/.zshrc"
    state: touch
  notify: remove dotconfigs

- name: remove dotconfigs
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - .config/mc/ini
    - .vim
    - .zsh
    - .gitconfig
    - .tmux.conf
    - .vimrc
    - .zlogin
    - .zlogout
    - .zshrc
  notify: create symlinks

- name: create symlinks
  file:
    src: '.dotfiles/{{ item }}'
    path: '{{ item }}'
    state: link
  with_items:
    - .vim
    - .zsh
    - .gitconfig
    - .tmux.conf
    - .vimrc
    - .zlogin
    - .zlogout
    - .zshrc
  notify: create MC config dir

- name: create MC config dir
  file:
    path: .config/mc
    state: directory
  notify: create MC ini symlink

- name: create MC ini symlink
  file:
    src: '../../.dotfiles/.config/mc/ini'
    path: '.config/mc/ini'
    state: link
...
