---
- name: PostgreSQL repos
  yum_repository:
    name: "pgdg{{ item|string|regex_replace('\\.', '') }}"
    description: "PostgreSQL {{ item|string }} $releasever - $basearch"
    baseurl: "https://download.postgresql.org/pub/repos/yum/{{ item|string }}/redhat/rhel-$releasever-$basearch"
    file: "pgdg-{{ item|string|regex_replace('\\.', '') }}-centos"
    gpgcheck: yes
    enabled: yes
    gpgkey: "http://ftp.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-{{ item|string|regex_replace('\\.', '') }}"
  loop: "{{ pwa_postgresql_versions|flatten(levels=1) }}"

- name: PostgreSQL packages
  yum:
    name: "postgresql{{ item.0|string|regex_replace('\\.', '') }}{{ item.1 }}"
  loop: "{{ pwa_postgresql_versions|product([ '', '-server', '-contrib' ])|list }}"

- name: Other packages
  yum:
    name: "{{ pwa_common_packages|union(pwa_add_packages) }}"

- name: mask services
  systemd:
    name: postgresql-{{ item|string }}.service
    enabled: no
    masked: yes
  loop: "{{ pwa_postgresql_versions|flatten(levels=1) }}"
  when: "ansible_service_mgr == 'systemd'"

- name: disable services
  service:
    name: postgresql-{{ item|string }}
    enabled: no
  loop: "{{ pwa_postgresql_versions|flatten(levels=1) }}"
  when: "ansible_service_mgr == 'upstart'"

...
