---
- name: Check requirements
  assert:
    that:
      - ansible_distribution_file_variety == 'RedHat'
      - ansible_distribution_major_version|int >= 6
      - inventory_hostname in groups['pg_wal_archive']

- name: walarchive section
  block:
    - name: Include users
      include_tasks: wa_user.yml

    - name: Include script
      include_tasks: wa_script.yml
  when: "'walarchive' in pwa_server_roles"

- name: basebackup section
  block:
    - name: Include packages
      include_tasks: bb_packages.yml

    - name: Include users
      include_tasks: bb_user.yml

    - name: Include script
      include_tasks: bb_script.yml
  when: "'basebackup' in pwa_server_roles"
...
