---
- name: Check role requirements
  assert:
    that:
      - ansible_distribution_file_variety == "RedHat"
      - ansible_distribution_major_version|int >= 5
      - bacula_director is defined
      - inventory_hostname not in groups['nobacula']

- name: Include packages
  include_tasks: packages.yml

- name: Include tls
  include_tasks: tls.yml
...
