---
- name: Section 5
  block:
    - name: Import aux/repos/endpoint galaxy role
      import_role:
        name: aux/repos/endpoint

    - name: Install bacula-fd package (V)
      yum:
        name: bacula-client-5.0.2
        enablerepo: endpoint
  when: ansible_distribution_major_version|int == 5

- name: Install bacula-fd package (VI)
  yum:
    name: bacula-client-5.0.0
  when: ansible_distribution_major_version|int == 6

- name: Install bacula-fd package (VII)
  yum:
    name: bacula-client-5.2.13
  when: ansible_distribution_major_version|int == 7
...
