---
- name: Stat password file
  stat:
    path: "/etc/bacula/passwd.{{ inventory_hostname }}"
  register: __bacula_fd_passwd_file

- name: Create password file if not exists
  copy:
    dest: "/etc/bacula/passwd.{{ inventory_hostname }}"
    content: >
      {{ lookup('password', '/dev/null chars=ascii_letters,digits,hexdigits') }}
  when: not __bacula_fd_passwd_file.stat.exists

- name: Slurp password
  slurp:
    src: "/etc/bacula/passwd.{{ inventory_hostname }}"
  register: __bacula_fd_passwd
...
