---
- name: Check if ifup-tunnel exists
  stat:
    path: /etc/sysconfig/network-scripts/ifup-tunnel
  register: __quagga_ospfd_ifup_tunnel_stat

- name: Patch ifup-tunnel
  patch:
    src: etc/sysconfig/network-scripts/ifup-tunnel.patch
    dest: /etc/sysconfig/network-scripts/ifup-tunnel
  when: __quagga_ospfd_ifup_tunnel_stat.stat.exists

- name: Template ospfd.conf
  template:
    src: etc/quagga/ospfd.conf.j2
    dest: /etc/quagga/ospfd.conf
    owner: quagga
    group: quagga
    mode: 0600
  notify: restart ospfd

- name: OSPFd service enabled
  service:
    name: ospfd
    enabled: yes
    state: started
...
