---
- name: Check role requirements
  assert:
    that:
      - ansible_distribution_file_variety == "RedHat"
      - ansible_distribution_major_version|int == 7

- name: Yum install quagga
  yum:
    name:
      - quagga
      - patch

- name: ospfd include
  include_tasks: ospfd.yml
  when: "'ospfd' in quagga_daemons"
...
