---
- name: Enable curl.so for php
  hosts: bx.all
  become: yes
  become_method: sudo
  vars:
    inifile: /etc/php.d/curl.ini

  tasks:
  - name: Enable curl.so
    lineinfile: dest={{ inifile }} line=extension=curl.so
    notify: reload httpd

  handlers:
    - name: reload httpd
      service: name=httpd state=reloaded


# vim:ft=ansible:
