---
- name: "User's crontab"
  cron:
    name: "{{ item.name }}"
    user: "{{ item.user }}"
    job: "{{ item.job }}"
    minute: "{{ item.minute|d('*') }}"
    hour: "{{ item.hour|d('*') }}"
    day: "{{ item.day|d('*') }}"
    weekday: "{{ item.weekday|d('*') }}"
    month: "{{ item.month|d('*') }}"
    disabled: "{{ item.disabled|d('false') }}"
    state: "{{ item.state|d(true)|ternary('present','absent') }}"
  with_items: "{{ common_cron_user_tasks }}"
  loop_control:
    label: "{{ item.user }}:{{ item.name }}"
  tags: [ cron ]
...
