---
- name: Stat check if already enrolled
  stat:
    path: /etc/ipa/default.conf
    get_attributes: no
    get_checksum: no
    get_mime: no
  register: common_reg_ipa
  tags: [ domain ]

- name: Enroll to IPA domain
  shell: >
    ipa-client-install --no-ntp --mkhomedir --no-dns-sshfp --principal {{ common_ipa_principal }} -w {{ common_ipa_password }} --unattended
  when: not common_reg_ipa.stat.exists
  notify: disable root ssh login
  tags: [ domain ]
...
