---
- name: Check hostname in /etc/sysconfig/network
  lineinfile:
    dest: "/etc/sysconfig/network"
    regexp: '^HOSTNAME='
    line: 'HOSTNAME={{ inventory_hostname }}'
  when: "ansible_service_mgr == 'upstart'"
  tags: [ hostname ]

- name: Check hostname
  hostname:
    name: "{{ inventory_hostname }}"
  tags: [ hostname ]

- name: Add record in /etc/hosts if alien
  lineinfile:
    path: /etc/hosts
    regexp: '^.*{{ inventory_hostname }}$'
    line: "{{ ansible_default_ipv4.address }}\t{{ inventory_hostname }}"
  when: alien
  tags: [ hostname ]

- name: Add block in /etc/hosts
  blockinfile:
    path: /etc/hosts
    owner: root
    mode: 0644
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR COMMON ROLE"
    block: |
      {% for hostname, address in common_etc_hosts|dictsort %}
      {{ address }}\\t\\t{{ hostname }}
      {% endfor %}
  when: common_etc_hosts|length > 0
...
