---
- name: "Remove lines from ifcfg"
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}
    state: absent
    regexp: "{{ item }}"
  with_items:
    - '^UUID='
    - '^DEFROUTE='
    - '^PEERDNS='
    - '^PEERROUTES='
    - '^IPV4_FAILURE_FATAL='
    - '^IPV6_'
  tags: [services,ifcfg]

- name: "Edit ifcfg"
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^IPV6INIT=', line: 'IPV6INIT=no' }
    - { regexp: '^HWADDR=', line: 'HWADDR={{ ansible_default_ipv4.macaddress }}' }
  tags: [services,ifcfg]
  ignore_errors: yes

