---
- name: When not NM section
  block:
    - name: "Remove lines from ifcfg"
      lineinfile:
        dest: "/etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}"
        state: absent
        regexp: "{{ item }}"
      loop:
        - '^DEFROUTE='
        - '^PEERROUTES='
        - '^IPV4_FAILURE_FATAL='
        - '^IPV6_'

    - name: "Edit ifcfg"
      lineinfile:
        dest: "/etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^IPV6INIT=', line: 'IPV6INIT="no"' }
      ignore_errors: yes
  when: not common_leave_networkmanager
  tags: [ services, ifcfg ]

- name: Ifcfg template section
  block:
    - name: Template ifcfg
      template:
        src: ifcfg.j2
        dest: "{{ common_network_scripts }}/ifcfg-{{ item.dev }}"
        owner: root
        group: root
        mode: 0644
      when: item.state|d(true)
      register: common_ifcfg_result
      loop: "{{ common_ifcfg }}"
      loop_control:
        label: "{{ item.dev }}"

    - name: Remove ifcfg
      file:
        path: "{{ common_network_scripts }}/ifcfg-{{ item.dev }}"
        state: absent
      when: not item.state|d(true)
      loop: "{{ common_ifcfg }}"
      loop_control:
        label: "{{ item.dev }}"
  when: common_ifcfg|length > 0
  tags: [ ifcfg ]

- name: Ifcfg line section
  block:
    - name: Include ifcfg loop
      include_tasks: ifcfg_vars.yml
      loop: "{{ common_ifcfg_vars }}"
      loop_control:
        loop_var: ifcfg
        label: "{{ ifcfg.dev }}"
  when: common_ifcfg_vars|length > 0
  tags: [ ifcfg ]

- name: Early initialize array
  set_fact:
    common_ifcfg_changed: []

- name: Interfaces restart section
  block:
    - name: Populate array with dev names of changed ifcfgs
      set_fact:
        common_ifcfg_changed: "{{ common_ifcfg_changed }} + [ '{{ item.item.dev }}' ]"
      when:
        - common_ifcfg_result.results is defined
        - item.changed
        - item.item.variables.ONBOOT|d('no') | regex_search('[Yy][Ee][Ss]')
      loop: "{{ common_ifcfg_result.results }}"
      loop_control:
        label: "{{ item.item.dev }}"

    - name: "Restart changed interfaces"
      shell: >
        ifdown {{ item }} ; ifup {{ item }}
      async: 45
      poll: 5
      when: common_ifcfg_changed|length > 0
      loop: "{{ common_ifcfg_changed|unique }}"
      loop_control:
        label: "{{ item }}"
      ignore_errors: yes
  when: common_ifcfg_restart
  tags: [ ifcfg ]
...
