---
- name: When not NM section
  block:
    - name: "Remove lines from ifcfg"
      lineinfile:
        dest: "/etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}"
        state: absent
        regexp: "{{ item }}"
      with_items:
        - '^UUID='
        - '^DEFROUTE='
        - '^PEERDNS='
        - '^PEERROUTES='
        - '^IPV4_FAILURE_FATAL='
        - '^IPV6_'
      tags: [ services, ifcfg ]

    - name: "Edit ifcfg"
      lineinfile:
        dest: "/etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^IPV6INIT=', line: 'IPV6INIT="no"' }
      tags: [ services, ifcfg ]
      ignore_errors: yes
  when: not common_leave_networkmanager

- name: "lineinfile add in network-scripts/ifcfg-"
  lineinfile:
    dest: "{{ common_network_scripts }}/ifcfg-{{ item.0.dev }}"
    regexp: '^[ #]*{{ item.1.key }}='
    line: '{{ item.1.key }}="{{ item.1.value|d("") }}"'
    state: "{{ item.1.state|d(true)|ternary('present','absent') }}"
    create: yes
  when: common_ifcfg_line is defined
  with_subelements:
    - "{{ common_ifcfg_line }}"
    - variables
  loop_control:
    label: "{{ item.0.dev }}:{{ item.1.key }}={{ item.1.value|d('') }}"
  register: common_ifcfg_result
  tags: [ ifcfg ]

- name: Initialize array
  set_fact:
    common_ifcfg_changed: []
  tags: [ ifcfg ]

- name: Populate array with dev names of changed ifcfgs
  set_fact:
    common_ifcfg_changed: "{{ common_ifcfg_changed }} + [ '{{ item.item[0].dev }}' ]"
  when:
    - common_ifcfg_result.results is defined
    - item.changed
  with_items: "{{ common_ifcfg_result.results }}"
  loop_control:
    label: "{{ item.item[0].dev }}"
  tags: [ ifcfg ]

- name: "Restart changed interfaces"
  shell: >
    ifdown {{ item }} ; ifup {{ item }}
  async: 45
  poll: 5
  when: common_ifcfg_changed|length > 0
  with_items: "{{ common_ifcfg_changed|unique }}"
  loop_control:
    label: "{{ item }}"
  ignore_errors: yes
  tags: [ ifcfg ]
...
