---
- name: "Template ipset config"
  template:
    src: "ipset.j2"
    dest: "/etc/sysconfig/ipset"
    force: no
  when:
    - '"bitrix-env" not in roles'
    - not alien
  tags: [ services, iptables, ipset ]
...
