---
- name: Template xt_recent parameters
  template:
    src: xt.conf.j2
    dest: "{{ xt_conf }}"
    owner: root
    group: root
    mode: 0644
  notify: xt_recent stop iptables
  tags: [ iptables, xt_recent ]

- meta: flush_handlers

- name: "Check iptables config presence"
  stat:
    path: "/etc/sysconfig/iptables"
  register: common_reg_ipt

- name: "Check SSH-DIRECT in iptables config"
  command: >
    cat /etc/sysconfig/iptables
  changed_when: false
  register: common_check_iptables
  when: common_reg_ipt.stat.exists

- name: Create empty dict
  command: >
    true
  register: common_check_iptables
  when: not common_reg_ipt.stat.exists

- name: "Copy IPTables config"
  copy:
    src: "{{ item }}"
    dest: /etc/sysconfig
    force: "{{ (ansible_user|d('UNDEF') == 'root')|ternary('yes','no') }}"
  with_items:
    - iptables
    - ip6tables
  when:
    - common_check_iptables.stdout.find('SSH-DIRECT') == -1
    - '"bitrix-env" not in roles'
  notify: config restart iptables
  tags: [ iptables ]
...
