---
- name: "Check SSH-DIRECT in iptables config"
  shell: "cat /etc/sysconfig/iptables"
  changed_when: false
  register: common_check_iptables

- name: "Copy IPTables config"
  copy:
    src: "{{ item }}"
    dest: /etc/sysconfig
    force: "{{ (ansible_user == 'root')|ternary('yes','no') }}"
  with_items:
    - iptables
    - ip6tables
  when:
    - common_check_iptables.stdout.find('SSH-DIRECT') == -1
    - '"bitrix-env" not in roles'
  notify: config restart iptables
  tags: [ iptables ]
...
