---
- name: Configure Journald
  ini_file:
    dest: /etc/systemd/journald.conf
    section: Journal
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { option: 'Storage', value: 'persistent' }
    - { option: 'Compress', value: 'yes' }
  notify: config restart journald
  when: ansible_distribution_major_version|int >= 7
  tags: [ services, journald ]

- name: Manage journal-gateway package
  yum:
    name: systemd-journal-gateway
    state: "{{ common_journal_gateway_enable|ternary('present','absent') }}"
  notify: "{{ common_journal_gateway_enable|ternary('config journal-gateway enable','dummy') }}"
  tags: [ services, journald ]
...
