---
- name: "Set inet_protocols in main.cf"
  replace:
    dest: /etc/postfix/main.cf
    regexp: 'inet_protocols = all'
    replace: 'inet_protocols = ipv4'
  tags: [ mail ]

- name: "Adding root alias in /etc/aliases"
  lineinfile:
    dest: /etc/aliases
    line: "root:\t\t{{ common_aliases_root }}"
  notify: config newaliases
  when: common_aliases_root is defined
  tags: [ mail ]
...
