---
- name: init.yml
  import_tasks: init.yml

- name: Import resolv
  import_tasks: resolv.yml

- name: Import packages1
  import_tasks: packages1.yml

- name: Import hostname
  import_tasks: hostname.yml

- name: Include mounts
  include_tasks: mounts.yml
  when: common_mounts|length > 0

- name: No-ct section
  block:
    - name: Include selinux
      include_tasks: selinux.yml

    - name: Include ifcfg
      include_tasks: ifcfg.yml

    - name: Include routes
      include_tasks: routes.yml
      when: common_static_route is defined

    - name: Include snmpd
      include_tasks: snmpd.yml

    - name: Include sysctl
      include_tasks: sysctl.yml
      when: common_sysctl_vars|length > 0
  when: "server_type != 'ct'"

- name: Include ntp
  include_tasks: ntp.yml

- name: Import mail
  import_tasks: mail.yml

- name: Include services
  include_tasks: services.yml

- name: Include journal
  include_tasks: journal.yml
  when: "ansible_service_mgr == 'systemd'"

- name: Import packages2
  import_tasks: packages2.yml

- name: Import colorize
  import_tasks: colorize.yml

- name: Import etckeeper
  import_tasks: etckeeper.yml

- name: Include cron
  include_tasks: cron.yml
  when:
    - common_cron_user_tasks|length > 0
  tags: [ cron ]

- name: Intranet section
  block:
    - name: Include console
      include_tasks: console.yml
      when:
        - ansible_virtualization_role == 'guest'
        - server_type != 'ct'

    - name: Include domain
      include_tasks: domain.yml

    - name: Include rsyslog
      include_tasks: rsyslog.yml
  when: not alien

- name: Include icinga2
  include_tasks: icinga2.yml
  when: >
    (not alien or ( alien and common_icinga2_enable ))
    and server_type != 'ct'
  tags: [ icinga2 ]

- meta: flush_handlers

- name: Reboot system if packages updated
  block:
    - name: Check if reboot is required
      command: >
        needs-restarting --reboothint
      ignore_errors: true
      register: reg_reboothint

    - name: Reboot block
      block:
        - name: Rebooting system
          shell: shutdown -r +1
          async: 0
          poll: 0
          ignore_errors: True
      when: reg_reboothint.rc == 1
  when:
    - pkgupdate
    - ansible_distribution_major_version|int >= 7

- name: Flush handlers
  meta: flush_handlers

...
