---
- import_tasks: packages1.yml

- import_tasks: hostname.yml

- import_tasks: porntube.yml

- import_tasks: ifcfg.yml

- import_tasks: ntp.yml

- import_tasks: snmpd.yml

- import_tasks: rsyslog.yml

- import_tasks: mail.yml

- import_tasks: services.yml

- import_tasks: console.yml
  when:
    - 'ansible_virtualization_role == "guest"'
    - not alien

- import_tasks: packages2.yml

- import_tasks: colorize.yml

- name: "Check if already enrolled"
  shell: "getent group sysadmins || :"
  register: common_getent_sysadmins
  changed_when: false
  tags: [domain]

- import_tasks: domain.yml
  when:
    - common_getent_sysadmins.stdout.find('sysadmins') == -1
    - not alien

- name: get first private address
  set_fact:
    common_ipv4_private: "{{ ansible_all_ipv4_addresses | ipaddr('private') | first }}"
  when:
    - not alien
  tags: [ icinga2 ]

- import_tasks: icinga2.yml
  when:
    - common_icinga2_enable
    - not alien
...
