---
- include_tasks: packages1.yml

- include_tasks: hostname.yml

- include_tasks: porntube.yml

- include_tasks: ifcfg.yml

- include_tasks: ntp.yml
  tags: [ ntp ]

- include_tasks: snmpd.yml

- include_tasks: rsyslog.yml

- include_tasks: mail.yml

- include_tasks: services.yml

- include_tasks: console.yml
  when:
    - 'ansible_virtualization_role == "guest"'
    - not alien

- include_tasks: packages2.yml

- include_tasks: colorize.yml

- name: "Check if already enrolled"
  shell: "getent group sysadmins || :"
  register: common_getent_sysadmins
  changed_when: false
  tags: [domain]

- include_tasks: domain.yml
  when:
    - common_getent_sysadmins.stdout.find('sysadmins') == -1
    - not alien
  tags: [domain]
...
