---
- name: Setup mounts
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src|d(omit) }}"
    fstype: "{{ item.fstype|d(omit) }}"
    opts: "{{ item.opts|d(omit) }}"
    state: "{{ item.state|d('mounted') }}"
  loop: "{{ common_mounts }}"

- name: Set modes
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.modes.owner|d(omit) }}"
    group: "{{ item.modes.group|d(omit) }}"
    mode: "{{ item.modes.mode|d(omit) }}"
  loop: "{{ common_mounts|selectattr('modes', 'defined')|list }}"
...
