---
- name: ntp.conf
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify: config restart ntpd
  tags: [ ntp ]

- name: "Set timezone"
  timezone:
    name: "{{ timezone }}"
  notify: config restart crond
  tags: [ ntp ]
...
