---
- name: "Remove unnecessary packages (YUM)"
  yum:
    name: "{{ common_unnecessary_packages }}"
    state: absent
  when: ansible_distribution == 'CentOS'
  tags: [packages]

- name: "Remove unnecessary packages (DNF)"
  dnf:
    name: "{{ common_unnecessary_packages }}"
    state: absent
  when: ansible_distribution == 'Fedora'
  tags: [packages]
...
