---
- name: ddns update multisite
  nsupdate:
    server: "{{ vhost_ddns_server }}"
    zone: "{{ bxvhost.ddns.zone|d(vhost_default_ddns_zone) }}"
    record: "{{ item.domain }}"
    type: "{{ bxvhost.ddns.type|d('CNAME') }}"
    value: "{{ bxvhost.ddns.value|d(ansible_fqdn ~ '.') }}"
    state: "{{ bxvhost.state|d(true)|ternary('present', 'absent') }}"
    key_name: "{{ vhost_ddns_key_name|d('ddns_key') }}"
    key_algorithm: "{{ vhost_ddns_key_algorithm|d('hmac-md5') }}"
    key_secret: "{{ vhost_ddns_key_secret }}"
  when:
    - bxvhost.ddns is defined
    - bxvhost.ddns.enable|d()
  with_items: "{{ bxvhost.multisite|d([]) }}"
  tags: [ ddns, multisite ]
...
