---
- name: get first private address
  set_fact:
    bx_ipv4_private: "{{ ansible_all_ipv4_addresses | ipaddr('private') | first }}"
  tags: [ webcheck ]

- name: determine if prod circuit
  set_fact:
    bx_circuit_prod: true
  when: bx_ipv4_private|ipaddr(item)
  with_items: "{{ common_icinga2_master_zone_net_list }}"
  tags: [ webcheck ]

- name: get nginx version
  shell: "nginx -V 2>&1 | awk '/nginx version:/ { print $3 }'"
  register: bx_reg_nginx_ver
  changed_when: no
  tags: [ version ]

- name: get php version
  shell: "php -v | awk '/PHP .* \\(cli\\)/ { print $2 }'"
  register: bx_reg_php_ver
  changed_when: no
  tags: [ version ]

- name: get apache version
  shell: "httpd -V | awk '/Server version:/ { print $3 }'"
  register: bx_reg_apache_ver
  changed_when: no
  tags: [ version ]

- name: get bitrix-env version
  command: rpm -q --qf "%{NAME}/%{VERSION}-%{RELEASE}" bitrix-env
  register: bx_reg_bxenv_ver
  changed_when: no
  tags: [ version ]

- name: set nginx and php version facts
  set_fact:
    bx_nginx_version: "{{ bx_reg_nginx_ver.stdout }}"
    bx_php_version: "php/{{ bx_reg_php_ver.stdout }}"
    bx_apache_version: "{{ bx_reg_apache_ver.stdout }}"
    bx_bxenv_version: "{{ bx_reg_bxenv_ver.stdout }}"
  tags: [ version ]

- name: get timestamp
  command: "date '+%FT%H%M'"
  register: bx_get_time
  changed_when: no
  tags: [ archive, db ]

- name: set timestamp
  set_fact:
    bx_timestamp: "{{ bx_get_time.stdout }}"
  tags: [ archive, db ]
...
