---
- name: "Template msmtprc"
  template:
    dest: "/etc/msmtprc"
    src: msmtprc.j2
    force: yes
    backup: yes
    # notify: link template msmtprc
  tags: [ mail ]

- name: "Adding bitrix alias in /etc/aliases"
  lineinfile:
    dest: /etc/aliases
    line: "bitrix:\t\t{{ bx_mail_alias }}"
  notify: config newaliases
  when: bx_mail_alias is defined
  tags: [ mail, mail_alias ]

- name: create msmtp log file
  copy:
    dest: "/var/log/msmtp.log"
    content: ""
    force: no
    mode: 0666
  tags: [ mail ]

- meta: flush_handlers
...
