---
- include: selinux.yml

- include: firewalld.yml

- name: "Check if bitrix-env already installed"
  command: getent passwd bitrix
  register: getent_bitrix
  changed_when: false
  failed_when: false
  tags: [bitrix-env]

# Install Bitrix-env
- name: "Download {{ bitrix_sh }}"
  get_url:
    dest: /var/local
    force: yes
    url: "http://repos.1c-bitrix.ru/yum/{{ bitrix_sh }}"
    mode: 0755
  when: getent_bitrix.stdout.find('bitrix') == -1
  tags: [bitrix-env]

- name: "Run {{ bitrix_sh }}"
  shell: "/var/local/{{ bitrix_sh }}"
  when: getent_bitrix.stdout.find('bitrix') == -1
  notify: set bitrix password
  tags: [bitrix-env]

- meta: flush_handlers

- include: nginx.yml

# - include: iptables.yml

- include: php.yml

- name: "Copy bxinit script"
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    force: yes
    owner: root
    group: root
    mode: 0744
  with_items:
    - "{{ bxinit_sh }}"
  tags: [scripts]

- name: "Template bxmult scripts"
  template:
    src: "{{ item }}.j2"
    dest: "/usr/local/bin/{{ item }}"
    force: yes
    owner: root
    group: root
    mode: 0744
  with_items:
    - "{{ bxmult_sh }}"
  tags: [scripts]

- name: "Copy .gitignore"
  copy:
    src: "gitignore"
    dest: "/home/bitrix/www/.gitignore"
    force: no
    owner: bitrix
    group: bitrix
    mode: 0644
  tags: [bitrix-env]

- include: mail.yml

- include: mysqld.yml
  when: not alien

- name: "Set bash prompt attributes [dev]"
  lineinfile:
    dest: /etc/bash.attr
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: '^PR_HOST=', line: 'PR_HOST=${PR_GREEN}' }
    - { regexp: '^PR_ATTRIB=', line: 'PR_ATTRIB=VM' }
  when: "'dev' in ansible_domain"
  tags: [prompt]

- name: "Set bash prompt attributes [prod]"
  lineinfile:
    dest: /etc/bash.attr
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: '^PR_HOST=', line: 'PR_HOST=${PR_RED}' }
    - { regexp: '^PR_ATTRIB=', line: 'PR_ATTRIB=VM' }
  when: "'dev' not in ansible_domain"
  tags: [prompt]

- name: "Add domain in /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    line: "127.0.1.1\t{{ ansible_fqdn }}"
    state: present
  tags: [hosts]

- name: "Print message"
  debug:
    msg: "PLEASE EDIT DOMAIN NAME IN /etc/msmtprc"
  when: "'dev' not in ansible_domain"
...
