---
- name: "MySQLd disabled (sysVinit)"
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - mariadb
    - mysqld
    - mysql
  when: ansible_distribution_major_version|int < 7
  ignore_errors: true
  tags: [ services ]

- name: "MySQLd masked (systemd)"
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    masked: yes
  with_items:
    - mariadb
    - mysqld
    - mysql
  when: ansible_distribution_major_version|int >= 7
  ignore_errors: true
  tags: [ services ]
...
