---
- name: "Create include.d directoty"
  file:
    path: "/etc/nginx/include.d"
    state: directory
  tags: [nginx_status]

- name: "Copy included status location file"
  copy:
    src: "bx_status.conf"
    dest: "/etc/nginx/include.d/bx_status.conf"
  notify: config restart nginx
  tags: [nginx_status]

- name: "Template allow status file"
  template:
    src: "allow_status.conf.j2"
    dest: "/etc/nginx/include.d/allow_status.conf"
  notify: config restart nginx
  tags: [nginx_status]

- name: "Add include block in bx/site_available/s1.conf"
  blockinfile:
    dest: "/etc/nginx/bx/site_avaliable/s1.conf"
    insertafter: 'include bx/conf/bitrix.conf;'
    block: |
      # Include server status page
      include /etc/nginx/include.d/bx_status.conf;
  notify: config restart nginx
  tags: [nginx_status]
...
