---
- name: restore normal system state
  import_role:
    name: common
  vars:
    pkgupdate: false
  when: bx_run_script.changed

- name: configure firewalld
  firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  with_items: [ ntp, snmp, http, bacula-client ]
  when: ansible_distribution_major_version|int >= 7
  tags: [ firewalld ]
...
