---
- name: generate ssh key
  user:
    name: bitrix
    generate_ssh_key: yes
    ssh_key_type: "{{ bxvhost['ssh_key_type']|d('ed25519') }}"
    state: present
  register: bx_user
  tags: [ user ]

- name: copy pubkey to authorized_keys
  copy:
    src: "{{ bx_user.ssh_key_file }}.pub"
    dest: "{{ bx_user.home }}/.ssh/authorized_keys"
    remote_src: yes
    force: no
    owner: bitrix
    group: bitrix
    mode: 0600
  when: bx_user.changed
  tags: [ user ]
...
