---
- name: "fetch new user's private key for lookup"
  fetch:
    src: "{{ bx_user.ssh_key_file }}"
    dest: "/tmp/bx_{{ ansible_fqdn }}_{{ bx_user.ssh_key_file|basename }}"
    flat: yes
  when:
    - bx_user.changed
    - bx_user.state == 'present'
  tags: [ wiki ]

- name: template wiki page
  template:
    src: "wiki.j2"
    dest: "/tmp/bx_{{ ansible_fqdn }}.txt"
  delegate_to: localhost
  become: no
  when:
    - bx_user.changed
    - bx_user.state == 'present'
  tags: [ wiki ]

- name: "delete new user's private key"
  file:
    state: absent
    path: "/tmp/bx_{{ ansible_fqdn }}_{{ bx_user.ssh_key_file|basename }}"
  delegate_to: localhost
  when:
    - bx_user.changed
    - bx_user.state == 'present'
  tags: [ wiki ]

- name: print a path to the wiki file
  debug:
    msg: "Wiki content: /tmp/bx_{{ ansible_fqdn }}.txt"
  when:
    - bx_user.changed
    - bx_user.state == 'present'
  tags: [ wiki ]
...
