---
- name: Check if role assigned to host
  fail:
    msg: "Role 'php-fpm' is not assigned to this host"
  when: "'php-fpm' not in roles"

- name: "Check required parameter"
  fail:
    msg: "Please add PHP version parameter (-e remi_php_version=56|70|71)"
  when:
    - remi_php_version is not defined
    - not php_fpm_oob

- include_tasks: packages.yml

- include_tasks: selinux.yml

- name: "Copy index.php"
  copy:
    dest: /var/www
    src: index.php
    force: yes
  tags: [index]

# PHP TIMEZONE
- stat: path=/etc/php.ini
  register: php_ini
  tags: [ php ]

- name: "Set timezone in php.ini [rh-based]"
  lineinfile:
    dest: "/etc/php.ini"
    regexp: '(^date.timezone\s*=\s*(?!{{ timezone|default(''Europe/Moscow'') }})|;date.timezone\s*=\s*)'
    line: 'date.timezone = {{ timezone|default(''Europe/Moscow'') }}'
  when: php_ini.stat.exists
  tags: [ php, timezone ]

# UMASK
- name: "Set umask for php-fpm service"
  blockinfile:
    dest: /etc/systemd/system/php-fpm.service.d/php-fpm.conf
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK: UMASK"
    block: |
      [Service]
      UMask=0002
  notify: config restart php-fpm
  tags: [services]

- name: Set ini ondemand for default pool
  ini_file:
    path: "/etc/php-fpm.d/www.conf"
    section: www
    option: pm
    value: ondemand
  notify: config reload php-fpm

- include_tasks: logrotate.yml

- include_tasks: memcached.yml
  when: php_fpm_memcached_client
  tags: [memcached]

- include_tasks: awstats.yml
...
