---
- name: Check if role assigned to host
  assert:
    that:
      - "'php-fpm' in server_roles"
    msg: "Role 'php-fpm' is not assigned to this host"

- import_tasks: packages.yml

- name: "Copy index.php"
  copy:
    dest: /var/www
    src: index.php
    force: yes
  tags: [ index ]

# UMASK
- name: "Set umask for php-fpm service"
  blockinfile:
    dest: /etc/systemd/system/php-fpm.service.d/php-fpm.conf
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK: UMASK"
    block: |
      [Service]
      UMask=0002
  notify: config restart php-fpm
  tags: [ services ]

- name: Set ini ondemand for default pool
  ini_file:
    path: "/etc/php-fpm.d/www.conf"
    section: www
    option: pm
    value: ondemand
  notify: config reload php-fpm

- name: Service enabled and started
  systemd:
    name: php-fpm.service
    state: started
    enabled: yes

- name: Template Laravel instantiated units
  template:
    src: "systemd/laravel-queue.j2"
    dest: "/etc/systemd/system/{{ item.name|d('laravel-queue-worker') }}@.service"
    owner: root
    group: root
    mode: 0644
  when:
    - php_laravel_units|length > 0
    - item.state|d(True)
  with_items: "{{ php_laravel_units }}"
  notify: systemd reload

- name: Remove Laravel instantiated units
  file:
    path: "/etc/systemd/system/{{ item.name|d('laravel-queue-worker') }}@.service"
    state: absent
  when:
    - php_laravel_units|length > 0
    - not item.state|d(True)
  with_items: "{{ php_laravel_units }}"
  notify: systemd reload

- include_tasks: logrotate.yml

- include_tasks: awstats.yml
...
