---
- name: Remi repo
  yum:
    name: "http://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    state: present
  when: not php_fpm_oob
  notify: enable remi repo
  tags: [ packages,remi ]

- meta: flush_handlers

- name: yum common packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - php-cli
    - php-fpm
    - php-pdo
    - php-xml
    - php-gd
    - php-intl
    - php-pgsql
    - php-mbstring
    - php-nette-tokenizer
    - python-psycopg2
    - MySQL-python
    - python-dns
  tags: [ packages ]

- name: yum Remi packages
  yum:
    name: "{{ item }}"
    state: present
  when: not php_fpm_oob
  with_items:
    - php-pecl-crypto
  tags: [ packages ]

- name: yum SELinux packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - libsemanage-python        # this packages required by selinux.xml
    - policycoreutils-python    #
  when: selinux_state != "disabled"
  tags: [ packages, selinux ]

- name: yum additional packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ php_fpm_add_packages }}"
  tags: [ packages ]
...
