---
- name: yum common packages
  yum:
    name: "{{ php_fpm_common_packages }}"
    state: present
  tags: [ packages ]

- name: yum additional packages
  yum:
    name: "{{ php_fpm_add_packages }}"
    state: present
  when: php_fpm_add_packages|length > 0
  notify: config reload php-fpm
  tags: [ packages ]
...
