---
- name: validate nginx
  command: "nginx -t"
  notify: reload nginx

- name: reload nginx
  systemd:
    name: "nginx.service"
    state: reloaded

- name: validate php-fpm
  command: "/sbin/php-fpm -t"
  notify: reload php-fpm

- name: reload php-fpm
  systemd:
    name: "php-fpm.service"
    state: reloaded

- name: repo git created
  shell: "cd {{ vhost_git_path }}/{{ item.repo.name|d(item.name|regex_replace('.' ~ vhost_default_ddns_zone ~ '$', '')) }}/hooks && ln -sv post-update.sample post-update && git update-server-info"
  args:
    creates: "{{ vhost_git_path }}/{{ item.repo.name|d(item.name|regex_replace('.' ~ vhost_default_ddns_zone ~ '$', '')) }}/hooks/post-update"
  when:
    - item.repo.type|d('none') == 'git'
    - item.state|d(true)
  with_items: "{{ vhost }}"
  delegate_to: "{{ vhost_git_server }}"
...
