---
- name: Check if role assigned to host
  assert:
    that:
      - inventory_hostname in groups['httpd']

- import_tasks: packages.yml

- name: Config section
  block:
    - name: Comment Listen directives
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^(Listen\s+[.:0-9]+)$'
        line: "#A \\1"
        backrefs: yes
      notify: config validate httpd restart

    - name: Insert include line
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        insertafter: "#A Listen"
        line: "Include conf/listen.conf"
      notify: config validate httpd restart

    - name: Template listen.conf
      template:
        src: listen.conf.j2
        dest: /etc/httpd/conf/listen.conf
        owner: root
        group: root
        mode: 0644
      notify: config validate httpd restart

    # MODULES
    - name: "Enable MPM-ITK"
      lineinfile:
        dest: "/etc/httpd/conf.modules.d/00-mpm-itk.conf"
        backrefs: yes
        regexp: '^.*LoadModule(\s+)mpm_(.*)$'
        line: 'LoadModule\1mpm_\2'
  tags: [ conf ]

# UMASK
- name: "Set umask for httpd service (sysconfig)"
  lineinfile:
    dest: "/etc/sysconfig/httpd"
    line: 'umask 002'
  notify: config validate httpd restart
  tags: [ services ]

- import_tasks: logrotate.yml

- include_tasks: awstats.yml
...
