---
- name: Add fcontexts
  sefcontext:
    setype: "{{ item.setype }}"
    target: "{{ item.target }}"
    state: present
  with_items:
    - name: "Crontab fix"
      setype: user_cron_spool_t
      target: '/var/spool/cron/[^/]*'
    - name: "Usual ssh dir"
      setype: ssh_home_t
      target: '/var/www/[-a-zA-Z0-9\.]+/\.ssh(/.*)?'
    - name: "Usual log dir"
      setype: httpd_log_t
      target: '/var/www/[-a-zA-Z0-9\.]+/log(/.*)?'
    - name: "Usual sessions dir"
      setype: httpd_cache_t
      target: '/var/www/[-a-zA-Z0-9\.]+/tmp(/.*)?'
    - name: "DkProtec engine: cache"
      setype: httpd_sys_rw_content_t
      target: '/var/www/[-a-zA-Z0-9\.]+/www/cache(/.*)?'
    - name: "DkProtec engine: uploads"
      setype: httpd_sys_rw_content_t
      target: '/var/www/[-a-zA-Z0-9\.]+/www/uploads(/.*)?'
    - name: "DkProtec engine: _synchro templates_c"
      setype: httpd_sys_rw_content_t
      target: '/var/www/[-a-zA-Z0-9\.]+/www/_synchro/templates_c(/.*)?'
    - name: "Laravel framework bootstrap cache"
      setype: httpd_sys_rw_content_t
      target: '/var/www/[-a-zA-Z0-9\.]+/www/bootstrap/cache(/.*)?'
    - name: "Laravel framework photos (webmech)"
      setype: httpd_sys_rw_content_t
      target: '/var/www/[-a-zA-Z0-9\.]+/www/public/photos(/.*)?'
    - name: "Laravel framework storage"
      setype: httpd_sys_rw_content_t
      target: '/var/www/[-a-zA-Z0-9\.]+/www/storage(/.*)?'
    - name: "Laravel framework storage logs"
      setype: httpd_sys_rw_content_t
      target: '/var/www/[-a-zA-Z0-9\.]+/www/storage/logs(/.*)?'
    - name: "CakePHP tmp"
      setype: httpd_sys_rw_content_t
      target: '/var/www/[-a-zA-Z0-9\.]+/www/app/tmp(/.*)?'
    - name: "Yii framework assets"
      setype: httpd_sys_rw_content_t
      target: '/var/www/[-a-zA-Z0-9\.]+/www/web/assets(/.*)?'
    - name: "Yii framework assets (?)"
      setype: httpd_sys_rw_content_t
      target: '/var/www/[-a-zA-Z0-9\.]+/www/assets(/.*)?'
    - name: "Yii framework runtime"
      setype: httpd_sys_rw_content_t
      target: '/var/www/[-a-zA-Z0-9\.]+/www/runtime(/.*)?'
  loop_control:
    label: "{{ item.setype }}:{{ item.name|d('Unnamed') }}:{{ item.target }}"
  notify: restorecon www

- name: Add fcontexts (custom)
  sefcontext:
    setype: "{{ item.setype }}"
    target: "{{ item.target }}"
    state: present
  with_items: "{{ selinux_custom_fcontexts }}"
  loop_control:
    label: "{{ item.setype }}:{{ item.name|d('Unnamed') }}:{{ item.target }}"
  notify: restorecon www
...
