---
- name: Check if role assigned to host
  assert:
    that:
      - "'selinux-for-web' in server_roles"
    msg: "Role 'selinux-for-web' is not assigned to this host"

- import_tasks: booleans.yml

- import_tasks: ports.yml

- import_tasks: fcontexts.yml

- import_tasks: module.yml
...
