---
- name: Check if role assigned to host
  fail:
    msg: "ROLE 'selinux-for-web' IS NOT ASSIGNED TO THIS HOST"
  when: "'selinux-for-web' not in roles"

- import_tasks: booleans.yml

- import_tasks: ports.yml

- import_tasks: fcontexts.yml

- import_tasks: module.yml
...
