---
- name: Set timezone php option
  ini_file:
    path: "{{ bx_custom_php_settings }}"
    section: Date
    option: "date.timezone"
    value: "{{ timezone }}"
  notify: reload httpd
  tags: [ php, timezone ]

- name: Custom php options
  ini_file:
    path: "{{ bx_custom_php_settings }}"
    section: PHP
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items: "{{ php_options }}"
  notify: reload httpd
  tags: [ php ]

- name: Enable PHP modules
  lineinfile:
    dest: "{{ item.dest }}"
    line: "{{ item.line }}"
    state: present
    create: yes
  with_items:
    - { dest: '/etc/php.d/20-curl.ini', line: 'extension=curl.so' }
  when: bx_curl_enable
  notify: reload httpd
  tags: [ php_modules, php ]
...
