---
- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: reload crond
  service:
    name: crond
    state: reloaded
...
