---
- name: restart nginx
  systemd:
    name: nginx.service
    state: restarted

- name: restart httpd
  systemd:
    name: httpd.service
    state: restarted
    daemon-reload: yes

- name: reload httpd
  systemd:
    name: httpd.service
    state: reloaded

- name: config newaliases
  command: newaliases

- name: config mysqld reboot
  command: shutdown -r +1
  ignore_errors: true
  async: 0
  poll: 0
...
