---
- name: PostgreSQL common RPM repository
  yum_repository:
    name: pgdg-common
    description: "PostgreSQL common RPMs for RHEL/CentOS $releasever - $basearch"
    baseurl: "https://download.postgresql.org/pub/repos/yum/common/redhat/rhel-$releasever-$basearch"
    file: pgdg-common-centos
    gpgcheck: yes
    enabled: yes
    gpgkey: http://ftp.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG

- name: PostgreSQL main RPM repository
  yum_repository:
    name: "pgdg{{ postgresql_version_norm }}"
    description: "PostgreSQL {{ postgresql_version_raw }} for RHEL/CentOS $releasever - $basearch"
    baseurl: "https://download.postgresql.org/pub/repos/yum/{{ postgresql_version_raw }}/redhat/rhel-$releasever-$basearch"
    file: "pgdg-{{ postgresql_version_norm }}-centos"
    gpgcheck: yes
    enabled: yes
    gpgkey: http://ftp.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG

- name: PostgreSQL packages
  yum:
    name:
      - postgresql{{ postgresql_version_norm }}
      - postgresql{{ postgresql_version_norm }}-server
      - postgresql{{ postgresql_version_norm }}-contrib

- name: Some other packages
  yum:
    name: "{{ postgresql_other_packages }}"

- name: Pacemaker rmlock packages
  yum:
    name: "{{ postgresql_pcmk_rmlock_packages }}"
  when:
    - postgresql_pcmk_enable|bool
    - postgresql_pcmk_rmlock_enable|bool

- name: Additional packages
  yum:
    name: "{{ postgresql_additional_packages }}"
  when: postgresql_additional_packages|length > 0
...
