---
- name: Check if role assigned to host
  assert:
    that:
      - "'icinga2' in server_roles"
    msg: "Role 'icinga2' is not assigned to this host"

- import_tasks: packages.yml

- name: enable service icinga2
  systemd:
    name: "icinga2.service"
    state: started
    enabled: yes

- name: replace files content in the conf.d
  copy:
    dest: "/etc/icinga2/conf.d/{{ item }}"
    content: "/**/\n"
  with_items: "{{ icinga2_wipe_confd }}"
  tags: [ wipe ]

- import_tasks: icingaweb2.yml
  when: icinga2_icingaweb2_node

- name: add user icinga to nagios group
  user:
    name: "icinga"
    groups: "nagios"
    append: yes
  notify: service icinga2 restart

- name: copy utils.pm
  copy:
    src: "/usr/lib64/nagios/plugins/utils.pm"
    remote_src: yes
    dest: "/usr/share/perl5/vendor_perl/utils.pm"
    force: no

- name: git clone or update PluginOptDir
  become: yes
  environment:
    HOME: "{{ icinga2_env_home }}"
    KRB5CCNAME: "KEYRING:persistent:{{ icinga2_env_uid }}:{{ icinga2_env_uid }}"
  git:
    repo: "{{ icinga2_plugin_opt_repo }}"
    dest: "{{ icinga2_plugin_opt_dir }}"
    accept_hostkey: yes
  ignore_errors: true

- import_tasks: keys.yml
  when: not icinga2_client_node

- import_tasks: sendxmpp.yml
  when: not icinga2_client_node

- import_tasks: pgsql.yml
  when: not icinga2_client_node

- import_tasks: ipmi.yml
  when: not icinga2_client_node

- import_tasks: wmi.yml
  when: not icinga2_client_node
...
