---
- name: Iptables whitelist
  template:
    src: "iptables/{{ postgresql_iptables_config }}.j2"
    dest: "{{ postgresql_sb_etc }}/{{ postgresql_iptables_config }}"
    mode: 0644
  register: postgresql_whitelist

- import_tasks: "iptables-sysvinit.yml"
  when: ansible_distribution_major_version|int <= 6

- import_tasks: "iptables-systemd.yml"
  when: ansible_distribution_major_version|int >= 7

- name: Iptables service check script
  template:
    src: "iptables/{{ postgresql_iptables_check_script }}.j2"
    dest: "{{ postgresql_sb_check }}/{{ postgresql_iptables_check_script }}"
    mode: 0755
...
