---
- name: "{{ postgresql_iptables_service }} service"
  template:
    src: "iptables/{{ postgresql_iptables_script }}.j2"
    dest: "/etc/init.d/{{ postgresql_iptables_service }}"
    mode: 0755

- name: "{{ postgresql_iptables_service }} service {{ postgresql_iptables_enable|ternary('enabled','disabled') }} (sysVinit)"
  service:
    name: "{{ postgresql_iptables_service }}"
    state: "{{ postgresql_iptables_enable|ternary('started','stopped') }}"
    enabled: "{{ postgresql_iptables_enable|ternary('yes','no') }}"

- name: "{{ postgresql_iptables_service }} service reloaded (sysVinit)"
  service:
    name: "{{ postgresql_iptables_service }}"
    state: reloaded
  when:
    - postgresql_iptables_enable|bool
    - postgresql_whitelist.changed
...
