---
- name: "{{ postgresql_iptables_service }} service script"
  template:
    src: "iptables/{{ postgresql_iptables_script }}.j2"
    dest: "{{ postgresql_sb_libexec }}/{{ postgresql_iptables_script }}"
    mode: 0744

- name: "{{ postgresql_iptables_service }} service unit"
  template:
    src: "iptables/{{ postgresql_iptables_service }}.service.j2"
    dest: "/etc/systemd/system/{{ postgresql_iptables_service }}.service"
    mode: 0644
  register: postgresql_iptables_unit

- name: "{{ postgresql_iptables_service }} service {{ postgresql_iptables_enable|ternary('enabled','disabled') }} (systemd)"
  systemd:
    name: "{{ postgresql_iptables_service }}"
    state: "{{ postgresql_iptables_enable|ternary('started','stopped') }}"
    enabled: "{{ postgresql_iptables_enable|ternary('yes','no') }}"

- name: "{{ postgresql_iptables_service }} service reloaded (systemd)"
  systemd:
    name: "{{ postgresql_iptables_service }}"
    state: reloaded
  when: postgresql_whitelist.changed

- name: "{{ postgresql_iptables_service }} service restarted (systemd)"
  systemd:
    name: "{{ postgresql_iptables_service }}"
    state: restarted
    daemon_reload: yes
  when: postgresql_iptables_unit.changed
...
