---
- name: PostgreSQL service masked
  systemd:
    name: "postgresql-{{ postgresql_version_raw }}"
    enabled: no
    masked: yes

- name: "Template custom config (pcmk)"
  become: yes
  become_user: "{{ postgresql_user }}"
  template:
    src: "{{ postgresql_custom_config_pcmk }}.j2"
    dest: "{{ postgresql_datadir }}/{{ postgresql_include_dir }}/{{ postgresql_custom_config_pcmk }}"
    mode: 0600
  notify: reload postgresql direct

- name: Archive and tmp dirs
  become: yes
  become_user: "{{ postgresql_user }}"
  file:
    path: "{{ postgresql_basedir }}/{{ item }}"
    state: directory
    mode: 0700
  with_items:
    - "pg_archive"
    - "tmp"

- name: "Directories for pcmk stuff"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ postgresql_pcmk_ra_dir }}"
    - "{{ postgresql_pcmk_rmlock_status|dirname }}"

- name: "Copy custom resource agent pgsql"
  copy:
    src: "resource-agents/pgsql"
    dest: "{{ postgresql_pcmk_ra_dir }}/pgsql"
    owner: root
    group: root
    mode: 0755
    force: "{{ postgresql_pcmk_force_ra_update|ternary('yes','no') }}"

- name: "Copy custom resource agent GCP"
  copy:
    src: "resource-agents/{{ item.path|basename }}"
    dest: "{{ item.path }}"
    owner: root
    group: root
    mode: "{{ item.mode|d('0644') }}"
    force: "{{ postgresql_pcmk_force_ra_update|ternary('yes','no') }}"
  when: postgresql_gcp_detect.stat.exists
  with_items:
    - path: "{{ postgresql_pcmk_ra_dir }}/gcp-vpc-move-ip"
      mode: "0755"
    - path: "/usr/share/man/man7/ocf_heartbeat_gcp-vpc-move-ip.7.gz"
  notify: update mandb

- name: "Template pcs init script"
  template:
    src: "pgsql.pcs.j2"
    dest: "{{ postgresql_pcmk_scripts_dir }}/pgsql.pcs"
    owner: root
    group: root
    mode: 0755
    force: "{{ postgresql_pcmk_force_pcs_update|ternary('yes','no') }}"

- name: "Template slave copy script"
  template:
    src: "pgsql-pcmk-slave-copy.sh.j2"
    dest: "{{ postgresql_pcmk_bin_dir }}/pgsql-pcmk-slave-copy.sh"
    owner: root
    group: root
    mode: 0755
    force: yes

- name: Periodic restart of pcsd
  cron:
    name: pcsd_restart
    job: "/usr/bin/systemctl restart pcsd.service"
    cron_file: "_sb_pcsd_restart"
    user: root
    hour: "*/{{ postgresql_pcmk_pcsd_restart_hour }}"
    minute: "{{ postgresql_pcmk_pcsd_restart_minute }}"
    state: "{{ postgresql_pcmk_pcsd_restart_enable|ternary('present','absent') }}"
...
