---
- name: Check if role assigned to host
  assert:
    that:
      - inventory_hostname in groups['icinga2']

- import_tasks: packages.yml

- name: enable service icinga2
  systemd:
    name: "icinga2.service"
    state: started
    enabled: yes

- name: replace files content in the conf.d
  copy:
    dest: "/etc/icinga2/conf.d/{{ item }}"
    content: "/**/\n"
  with_items: "{{ icinga2_wipe_confd }}"
  tags: [ wipe ]

- include_tasks: icingaweb2.yml
  when: icinga2_icingaweb2_node

- name: add user icinga to nagios group
  user:
    name: "icinga"
    groups: "nagios"
    append: yes
  notify: service icinga2 restart

- name: Root key import
  import_tasks: keys_root.yml

- name: copy utils.pm
  copy:
    src: "/usr/lib64/nagios/plugins/utils.pm"
    remote_src: yes
    dest: "/usr/share/perl5/vendor_perl/utils.pm"
    force: no

- name: git clone or update PluginOptDir
  become: yes
  environment:
    HOME: "{{ icinga2_env_home }}"
    KRB5CCNAME: "KEYRING:persistent:{{ icinga2_env_uid }}:{{ icinga2_env_uid }}"
  git:
    repo: "{{ icinga2_plugin_opt_repo }}"
    dest: "{{ icinga2_plugin_opt_dir }}"
    accept_hostkey: yes
  ignore_errors: true

- name: Nodes section
  block:
    - include_tasks: keys.yml
    - include_tasks: sendxmpp.yml
    - include_tasks: pgsql.yml
    - include_tasks: ipmi.yml
    - include_tasks: wmi.yml
  when: not icinga2_client_node

- name: Include http config
  template:
    src: config/http.j2
    dest: "/etc/icinga2/zones.d/{{ item[0].check_location }}/http/{{ item[1].name }}.conf"
    mode: "0644"
  loop: "{{ icinga2_config_http|subelements('domains', skip_missing=True) }}"
  loop_control:
    label: "{{ item[0].check_location }} : {{ item[1].name }}"
  notify: service icinga2 reload
...
