---
- name: PostgreSQL common RPM repository
  yum_repository:
    name: pgdg-common
    description: "PostgreSQL common RPMs for RHEL/CentOS $releasever - $basearch"
    baseurl: "https://download.postgresql.org/pub/repos/yum/common/redhat/rhel-$releasever-$basearch"
    file: pgdg-common-centos
    gpgcheck: yes
    enabled: yes
    gpgkey: http://ftp.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG
  tags: [ pgsql ]

- name: PostgreSQL main RPM repository
  yum_repository:
    name: "pgdg{{ postgresql_version_norm }}"
    description: "PostgreSQL {{ postgresql_version_raw }} for RHEL/CentOS $releasever - $basearch"
    baseurl: "https://download.postgresql.org/pub/repos/yum/{{ postgresql_version_raw }}/redhat/rhel-$releasever-$basearch"
    file: "pgdg-{{ postgresql_version_norm }}-centos"
    gpgcheck: yes
    enabled: yes
    gpgkey: http://ftp.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG
  tags: [ pgsql ]

- name: install postgresql
  yum:
    name:
      - "postgresql{{ postgresql_version_norm }}"
      - authd
    state: present
  tags: [ pgsql ]

- name: enable authd
  systemd:
    name: "auth.socket"
    state: started
    enabled: yes
  tags: [ ident ]

- name: set systemd LogLevel
  lineinfile:
    path: "/etc/systemd/system.conf"
    regexp: 'LogLevel='
    line: 'LogLevel=info'
  tags: [ ident ]

- name: authd override dir
  file:
    path: "/etc/systemd/system/auth@.service.d"
    state: directory
  tags: [ ident ]

- name: disable authd encryption
  copy:
    src: "authd.override.conf"
    dest: "/etc/systemd/system/auth@.service.d/override.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart authd
  tags: [ ident ]
...
