---
- name: Remove old python3.4
  yum:
    name: python34*
    state: absent

- name: yum install pip3
  yum:
    name: "python36-pip"
    state: present
  notify: pip installed

- name: pip install modules
  pip:
    executable: pip3
    name:
      - dnspython
      - sleekxmpp

- name: clone sendxmpp git repository
  git:
    repo: "https://github.com/moparisthebest/sendxmpp-py.git"
    dest: "sendxmpp-py"
    update: no

- name: copy sendxmpp script
  copy:
    src: "sendxmpp-py/sendxmpp"
    dest: "/usr/local/bin/sendxmpp.py"
    remote_src: yes
    mode: "0755"

- name: sendxmpp config directory
  file:
    state: directory
    path: "{{ icinga2_home }}/.config"
    owner: icinga
    group: icinga
    mode: "0755"

- name: template sendxmpp config
  template:
    src: "sendxmpp.cfg.j2"
    dest: "{{ icinga2_home }}/.config/sendxmpp.cfg"
    owner: icinga
    group: icinga
    mode: "0644"

- name: stat sendxmpp log file
  stat:
    path: /var/log/sendxmpp.log
  register: __icinga2_sendxmpp_log

- name: create sendxmpp log file
  file:
    state: touch
    path: /var/log/sendxmpp.log
  when: not __icinga2_sendxmpp_log.stat.exists

- name: set sendxmpp log perms
  file:
    path: /var/log/sendxmpp.log
    owner: icinga
    group: icinga
    mode: "0644"
...
