---
- name: Stat atomic repo
  stat:
    path: /etc/yum.repos.d/atomic.repo
  register: icinga2_reg_atomic

- name: install atomic repo
  yum:
    name: "{{ icinga2_atomic_rpm }}"
  when: not icinga2_reg_atomic.stat.exists
  tags: [ wmi ]

- name: install openvas-smb package
  yum:
    name: "openvas-smb"
    state: present
  tags: [ wmi ]

- name: template wmi auth file
  template:
    src: "wmi.common.auth.j2"
    dest: "/etc/icinga2/wmi.common.auth"
    mode: 0644
  tags: [ wmi ]
...
