---
- name: Template Apache vhost config
  template:
    src: "apache{{ (vhost_backend == 'bitrix')|ternary('-bx','') }}.j2"
    dest: "/etc/httpd/{{ (vhost_backend == 'bitrix')|ternary('bx/custom','conf.d') }}/{{ item.user|d(item.name) }}.conf"
    mode: 0644
    backup: yes
    force: "{{ item.legacy|d()|ternary('no', 'yes') }}"
  when:
    - item.nginx_301_only is not defined
    - item.backend_enable|d(True)
  loop: "{{ vhost|rejectattr('state', 'sameas', false)|list }}"
  loop_control:
    label: "{{ item.name }}"
  notify: validate apache
  tags: [ conf ]

- name: Remove Apache vhost config
  file:
    path: "/etc/httpd/{{ (vhost_backend == 'bitrix')|ternary('bx/custom','conf.d') }}/{{ item.user|d(item.name) }}.conf"
    state: absent
    backup: yes
  when: item.nginx_301_only is not defined
  loop: "{{ vhost|selectattr('state', 'sameas', false)|list }}"
  loop_control:
    label: "{{ item.name }}"
  notify: validate apache
  tags: [ conf ]

- name: Template HTTPd logrotate config
  template:
    src: logrotate/httpd.j2
    dest: "/etc/logrotate.d/httpd_{{ item.user|d(item.name) }}"
    owner: root
    group: root
    mode: 0644
  when: item.nginx_301_only is not defined
  loop: "{{ vhost|rejectattr('state', 'sameas', false)|list }}"
  loop_control:
    label: "httpd_{{ item.user|d(item.name) }}"

- name: HTTPd logrotate config absent
  file:
    path: "/etc/logrotate.d/httpd_{{ item.user|d(item.name) }}"
    state: absent
  loop: "{{ vhost|selectattr('state', 'sameas', false)|list }}"
  loop_control:
    label: "httpd_{{ item.user|d(item.name) }}"
...
