---
- name: Local facts
  set_fact:
    multi_dir: "{{ vhost_basedir }}/{{ multi[0].user|d(multi[0].name) }}/{{ multi[1].name | regex_replace('.' ~ vhost_default_ddns_zone ~ '$', '') }}"
    multi_user: "{{ multi[0].user|d(multi[0].name) }}"
  tags: [ crypto ]

- name: Multisite dirs
  file:
    path: "{{ multi_dir }}"
    state: directory
    owner: "{{ multi_user }}"
    group: "{{ multi_user }}"
    mode: 0770

- name: Multisite links
  file:
    path: "{{ multi_dir }}/{{ item }}"
    state: link
    src: "../www/{{ item }}"
    owner: "{{ multi_user }}"
    group: "{{ multi_user }}"
    force: yes
    follow: no
  loop: [ 'bitrix', 'upload' ]

- name: Multisite crypto
  block:
    - name: Multisite certificates
      copy:
        src: "{{ inventory_dir }}/../files/crypto/{{ multi[1].name }}.crt"
        dest: "/etc/pki/tls/certs/"
        owner: root
        group: root
        mode: 0644
      notify: validate nginx

    - name: Multisite keys
      copy:
        src: "{{ inventory_dir }}/../files/crypto/{{ multi[1].name }}.key"
        dest: "/etc/pki/tls/private/"
        owner: root
        group: root
        mode: 0400
      notify: validate nginx
  when:
    - multi[1].crypto|d('none') != 'none'
    - not multi[0].crypto_le|d()
  tags: [ crypto ]

- name: Check if LE certificate present
  stat:
    path: "/etc/letsencrypt/live/{{ multi[0].name }}/cert.pem"
  register: vhost_reg_le_check_multi
  tags: [ crypto ]

- name: Present .htsecure if redirect
  copy:
    dest: "{{ multi_dir }}/.htsecure"
    content: >
      # THIS FILE IS MANAGED BY ANSIBLE
    owner: "{{ multi_user }}"
    group: "{{ multi_user }}"
    mode: 0644
  when: >
    ( multi[1].crypto|d('none') == 'redirect' and not multi[0].crypto_le|d() )
    or ( multi[1].crypto|d('none') == 'redirect' and multi[0].crypto_le|d() and vhost_reg_le_check_multi.stat.exists )
  tags: [ crypto ]

- name: Absent .htsecure if no redirect
  file:
    path: "{{ multi_dir }}/.htsecure"
    state: absent
  when: >
    ( multi[1].crypto|d('none') != 'redirect' )
    or ( multi[1].crypto|d('none') == 'redirect' and multi[0].crypto_le|d() and not vhost_reg_le_check_multi.stat.exists )
  tags: [ crypto ]
...
