---
- name: copy certificates
  copy:
    src: "{{ inventory_dir }}/../files/crypto/{{ item.idna|d()|ternary(item.name.encode('idna'), item.name) }}.crt"
    dest: "/etc/pki/tls/certs/"
    owner: root
    group: root
    mode: 0644
  loop: >
    {{ vhost
    |rejectattr('state', 'sameas', false)
    |rejectattr('legacy', 'sameas', true)
    |selectattr('crypto', 'defined')
    |rejectattr('crypto', 'equalto', 'none')
    |rejectattr('crypto_le', 'sameas', true)
    |rejectattr('crypto_wildcard', 'sameas', true)
    |list }}
  loop_control:
    label: "{{ item.name }}"
  notify: validate nginx
  tags: [ crypto ]

- name: copy keys
  copy:
    src: "{{ inventory_dir }}/../files/crypto/{{ item.idna|d()|ternary(item.name.encode('idna'), item.name) }}.key"
    dest: "/etc/pki/tls/private/"
    owner: root
    group: root
    mode: 0400
  loop: >
    {{ vhost
    |rejectattr('state', 'sameas', false)
    |rejectattr('legacy', 'sameas', true)
    |selectattr('crypto', 'defined')
    |rejectattr('crypto', 'equalto', 'none')
    |rejectattr('crypto_le', 'sameas', true)
    |rejectattr('crypto_wildcard', 'sameas', true)
    |list }}
  loop_control:
    label: "{{ item.name }}"
  notify: validate nginx
  tags: [ crypto ]

- name: copy mobile certificates
  copy:
    src: "{{ inventory_dir }}/../files/crypto/m.{{ item.idna|d()|ternary(item.name.encode('idna'), item.name) }}.crt"
    dest: "/etc/pki/tls/certs/"
    owner: root
    group: root
    mode: 0644
  when: item.crypto_mobile|d('') != 'none'
  loop: >
    {{ vhost
    |rejectattr('state', 'sameas', false)
    |rejectattr('legacy', 'sameas', true)
    |selectattr('mobile', 'sameas', true)
    |selectattr('crypto', 'defined')
    |rejectattr('crypto', 'equalto', 'none')
    |rejectattr('crypto_le', 'sameas', true)
    |rejectattr('crypto_wildcard', 'sameas', true)
    |list }}
  loop_control:
    label: "{{ item.name }}"
  notify: validate nginx
  tags: [ crypto ]

- name: copy mobile keys
  copy:
    src: "{{ inventory_dir }}/../files/crypto/m.{{ item.idna|d()|ternary(item.name.encode('idna'), item.name) }}.key"
    dest: "/etc/pki/tls/private/"
    owner: root
    group: root
    mode: 0400
  when: item.crypto_mobile|d('') != 'none'
  loop: >
    {{ vhost
    |rejectattr('state', 'sameas', false)
    |rejectattr('legacy', 'sameas', true)
    |selectattr('mobile', 'sameas', true)
    |selectattr('crypto', 'defined')
    |rejectattr('crypto', 'equalto', 'none')
    |rejectattr('crypto_le', 'sameas', true)
    |rejectattr('crypto_wildcard', 'sameas', true)
    |list }}
  loop_control:
    label: "{{ item.name }}"
  notify: validate nginx
  tags: [ crypto ]

- name: copy wildcard certificates
  copy:
    src: "{{ inventory_dir }}/../files/crypto/{{ item.name|regex_replace('^(.*\\.)?([-a-zA-Z0-9]+\\.[a-zA-Z]+)$', '_\\2') }}.crt"
    dest: "/etc/pki/tls/certs/"
    owner: root
    group: root
    mode: 0644
  loop: >
    {{ vhost
    |rejectattr('state', 'sameas', false)
    |rejectattr('legacy', 'sameas', true)
    |selectattr('crypto', 'defined')
    |selectattr('crypto_wildcard', 'sameas', true)
    |rejectattr('crypto', 'equalto', 'none')
    |rejectattr('crypto_le', 'sameas', true)
    |list }}
  loop_control:
    label: "{{ item.name }}"
  notify: validate nginx
  tags: [ crypto ]

- name: copy wildcard keys
  copy:
    src: "{{ inventory_dir }}/../files/crypto/{{ item.name|regex_replace('^(.*\\.)?([-a-zA-Z0-9]+\\.[a-zA-Z]+)$', '_\\2') }}.key"
    dest: "/etc/pki/tls/private/"
    owner: root
    group: root
    mode: 0400
  loop: >
    {{ vhost
    |rejectattr('state', 'sameas', false)
    |rejectattr('legacy', 'sameas', true)
    |selectattr('crypto', 'defined')
    |selectattr('crypto_wildcard', 'sameas', true)
    |rejectattr('crypto', 'equalto', 'none')
    |rejectattr('crypto_le', 'sameas', true)
    |list }}
  loop_control:
    label: "{{ item.name }}"
  notify: validate nginx
  tags: [ crypto ]
...
