---
- name: Set htpasswd
  htpasswd:
    path: "{{ op.user_file|d(vhost_default_htpasswd) }}"
    name: "{{ item.name }}"
    password: "{{ item.pass }}"
    state: "{{ item.state|d(True)|ternary('present','absent') }}"
    owner: root
    group: nginx
    mode: 0640
  loop: "{{ op.nginx_auth_basic.users }}"
  loop_control:
    label: "{{ op.name }}:{{ item.name }}"
...
