---
- name: Disable Laravel instantiated units
  systemd:
    name: "{{ item[1].name|d('laravel-queue-worker') }}@{{ item[0].user|d(item[0].name) }}"
    state: stopped
    enabled: no
  loop: "{{ vhost|selectattr('state', 'sameas', false)|list|subelements('php_laravel_units', skip_missing=True) }}"
  loop_control:
    label: "{{ item[1].name|d('laravel-queue-worker') }}@{{ item[0].user|d(item[0].name) }}"

- name: Remove custom sudoers
  file:
    path: "/etc/sudoers.d/vhost_{{ item.user|d(item.name) }}"
    state: absent
  loop: "{{ vhost|selectattr('state', 'sameas', false)|selectattr('php_laravel_units', 'defined')|list }}"
  loop_control:
    label: "{{ item.user|d(item.name) }}"
...
