---
- name: Manage Laravel instantiated units
  systemd:
    name: "{{ item[1].name|d('laravel-queue-worker') }}@{{ item[0].user|d(item[0].name) }}"
    enabled: "{{ item[1].enabled|d(True)|ternary('yes','no') }}"
    state: "{{ item[1].enabled|d(True)|ternary('started','stopped') }}"
  loop: "{{ vhost|rejectattr('state', 'sameas', false)|list|subelements('php_laravel_units', skip_missing=True) }}"
  loop_control:
    label: "{{ item[1].name|d('laravel-queue-worker') }}@{{ item[0].user|d(item[0].name) }}"

- name: Template custom sudoers
  template:
    src: sudoers_d_laravel.j2
    dest: "/etc/sudoers.d/vhost_laravel_{{ item.user|d(item.name)|regex_replace('\.', '_') }}"
    owner: root
    group: root
    mode: 0440
  loop: "{{ vhost|rejectattr('state', 'sameas', false)|selectattr('php_laravel_units', 'defined')|list }}"
  loop_control:
    label: "{{ item.user|d(item.name) }}"

- name: Logrotate section
  block:
    - name: Template Laravel logrotate config
      template:
        src: logrotate/laravel.j2
        dest: "/etc/logrotate.d/laravel_{{ item.user|d(item.name) }}"
        owner: root
        group: root
        mode: 0644
      when: item.nginx_301_only is not defined
      loop: "{{ vhost|rejectattr('state', 'sameas', false)|list }}"
      loop_control:
        label: "laravel_{{ item.user|d(item.name) }}"

    - name: Laravel logrotate config absent
      file:
        path: "/etc/logrotate.d/laravel_{{ item.user|d(item.name) }}"
        state: absent
      loop: "{{ vhost|selectattr('state', 'sameas', false)|list }}"
      loop_control:
        label: "laravel_{{ item.user|d(item.name) }}"
  when: vhost_logrotate_laravel_enable
...
