---
- name: Check if role assigned to host
  fail:
    msg: "ROLE 'php' IS NOT ASSIGNED TO THIS HOST"
  when: "'php' not in roles"

- name: Check required parameter
  fail:
    msg: "Please set PHP version variable"
  when:
    - php_remi_version is not defined
    - not php_oob

- import_tasks: packages.yml

- name: "Set timezone in php.ini [rh-based]"
  lineinfile:
    dest: "/etc/php.ini"
    regexp: '(^date.timezone\s*=\s*(?!{{ timezone|default("Europe/Moscow") }})|;date.timezone\s*=\s*)'
    line: 'date.timezone = {{ timezone|default("Europe/Moscow") }}'
    create: no
  tags: [ timezone ]

- name: Memcached PHP module settings
  lineinfile:
    path: "/etc/php.d/50-memcached.ini"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items:
    - { regexp: '^;?(memcached.sess_prefix\s+=\s+")\w+(\.\w+\.\w+\.")', line: '\1{{ ansible_hostname }}\2' }
    - { regexp: '^;?(memcached.sess_consistent_hash\s+=\s+)[Oon]+', line: '\1On' }
    - { regexp: '^;?(memcached.sess_binary.*\s+=\s+)[Oon]+', line: '\1On' }
    - { regexp: '^;?(memcached.sess_number_of_replicas\s+=\s+)\d+', line: '\g<1>{{ php_memcached_nubmer_of_replicas }}' }
  when: php_memcached_client
  tags: [ memcached ]
...
