---
- name: Check role requirements
  assert:
    that:
      - inventory_hostname in groups['php_fpm'] or inventory_hostname in groups['httpd']
      - ansible_distribution_major_version|int >= 7
      - php_remi_version is defined or php_oob

- import_tasks: packages.yml

- name: "Timezone in php.ini [rh-based]"
  ini_file:
    path: "/etc/php.ini"
    section: Date
    option: date.timezone
    value: "{{ timezone|default('Europe/Moscow') }}"
    create: no
  notify: reload php
  tags: [ timezone ]

- name: Custom php.ini options
  ini_file:
    path: "/etc/php.ini"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    create: no
  notify: reload php
  with_items: "{{ php_options }}"

- name: Memcached PHP module settings
  lineinfile:
    path: "/etc/php.d/50-memcached.ini"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items:
    - { regexp: '^;?(memcached.sess_prefix\s+=\s+")\w+(\.\w+\.\w+\.")', line: '\1{{ ansible_hostname }}\2' }
    - { regexp: '^;?(memcached.sess_consistent_hash\s+=\s+)[Oon]+', line: '\1On' }
    - { regexp: '^;?(memcached.sess_binary.*\s+=\s+)[Oon]+', line: '\1On' }
    - { regexp: '^;?(memcached.sess_number_of_replicas\s+=\s+)\d+', line: '\g<1>{{ php_memcached_nubmer_of_replicas }}' }
  when: php_memcached_client
  tags: [ memcached ]

- import_tasks: git.yml
...
