---
- name: Check if role assigned to host
  assert:
    that:
      - inventory_hostname in groups['selinux_web']

- import_tasks: booleans.yml

- import_tasks: ports.yml

- import_tasks: fcontexts.yml

- import_tasks: module.yml
...
