---
- name: Check if role assigned to host
  assert:
    that:
      - inventory_hostname in groups['pgbouncer']
      - ansible_distribution_major_version|int >= 7
    msg: "Role 'pgbouncer' is not assigned to this host or other requirement is not satisfied"

- import_tasks: "packages.yml"
  tags: [ packages ]

- name: Ensure file userlist.txt exists
  copy:
    dest: "/etc/pgbouncer/userlist.txt"
    content: ""
    force: no
    owner: root
    group: root
    mode: 0755

- name: Set values in the INI config file ([pgbouncer])
  ini_file:
    path: "/etc/pgbouncer/pgbouncer.ini"
    section: pgbouncer
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { option: 'auth_type', value: 'md5' }
    - { option: 'ignore_startup_parameters', value: 'extra_float_digits' }
    - { option: 'idle_transaction_timeout', value: "{{ pgbouncer_config['idle_transaction_timeout']|d('7200') }}" }
    - { option: 'listen_addr', value: "{{ pgbouncer_config['listen_addr']|d('127.0.0.1') }}" }
    - { option: 'listen_port', value: "{{ pgbouncer_config['listen_port']|d('6432') }}" }
  notify: pgbouncer restart

- name: Insert ANSIBLE MANAGED mark
  lineinfile:
    path: "/etc/pgbouncer/pgbouncer.ini"
    line: ";; ANSIBLE MANAGED"
    regexp: '^;+\s*ANSIBLE MANAGED'
    insertafter: '^\[databases\]\s*$'

- name: Manage pgbouncer service
  systemd:
    name: pgbouncer.service
    enabled: "{{ pgbouncer_enable|ternary('yes','no') }}"
    state: "{{ pgbouncer_enable|ternary('started','stopped') }}"
...
