---
- name: "Install required packages (YUM)"
  yum: state=present name={{ item }}
  with_items:
    - squid
    - ipset
  when: ansible_distribution == "CentOS"
  tags: [packages]

- name: "Install required packages for CentOS 7 (YUM)"
  yum: state=present name={{ item }}
  with_items:
    - ipset-service
    - iptables-services
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int >= 7
  tags: [packages]

