---
- name: check if homedir exists
  stat:
    path: "{{ vhost_basedir }}/{{ item.user|d(item.name) }}"
  register: vhost_reg_home
  when:
    - item.changed
    - item.state == 'absent'
  loop: "{{ vhost_user.results }}"
  loop_control:
    label: "{{ item.name|d('null') }}"
  tags: [ archive ]

- name: remove logs and tmp from homedir
  file:
    path: "{{ item.0.stat.path }}/{{ item.1 }}"
    state: absent
  when:
    - item.0.stat is defined
    - item.0.stat.path is defined
    - not item.0.skipped|d()
  loop: "{{ vhost_reg_home.results|product([ 'log', 'logs', 'tmp' ])|list }}"
  loop_control:
    label: "{{ item.0.item.name|d('null') }}: {{ item.1 }}"
  ignore_errors: yes
  tags: [ archive ]

- name: Attempt to archive home directory
  block:
    - name: archive homedir
      archive:
        path:
          - "{{ item.stat.path }}"
        dest: "{{ vhost_preserve }}/{{ item.stat.path|basename }}-{{ vhost_timestamp }}.tar.gz"
        format: gz
        exclude_path:
          - "{{ item.stat.path }}/tmp/*"
          - "{{ item.stat.path }}/log/*"
          - "{{ item.stat.path }}/*.tar*"
          - "{{ item.stat.path }}/*.gz"
          - "{{ item.stat.path }}/*.zip"
          - "{{ item.stat.path }}/*.bz2"
          - "{{ item.stat.path }}/www/bitrix/backup/*"
          - "*.log"
      when:
        - item.stat is defined
        - item.stat.path is defined
        - not item.skipped|d()
      loop: "{{ vhost_reg_home.results }}"
      loop_control:
        label: "{{ item.item.name|d('null') }}"
      tags: [ archive ]
  rescue:
    - name: Create user back if archive error
      user:
        name: "{{ item[0].user|d(item[0].name) }}"
        create_home: no
        state: present
      when:
        - item[1].state == 'absent'
        - item[1].changed
      loop: "{{ vhost|zip(vhost_user.results)|list }}"
      loop_control:
        label: "{{ item[0].user|d(item[0].name) }}"
      tags: [ archive ]

    - name: Exit
      fail:
        msg: "HOMEDIR ARCHIVE ERROR"
      tags: [ archive ]

- name: remove homedir
  file:
    path: "{{ item.stat.path }}"
    state: absent
  when:
    - item.stat is defined
    - item.stat.path is defined
    - not item.skipped|d()
  loop: "{{ vhost_reg_home.results }}"
  loop_control:
    label: "{{ item.item.name|d('null') }}"
  ignore_errors: yes
  tags: [ archive ]
...
