---
- name: check if homedir exists
  stat:
    path: "{{ vhost_basedir }}/{{ item.user|d(item.name) }}"
  register: vhost_reg_home
  when:
    - item.changed
    - item.state == 'absent'
  with_items: "{{ vhost_user.results }}"
  loop_control:
    label: "{{ item.name }}"
  tags: [ archive ]

- name: archive homedir
  archive:
    path:
      - "{{ item.stat.path }}"
    dest: "{{ vhost_preserve }}/{{ item.stat.path|basename }}-{{ vhost_timestamp }}.tar.gz"
    format: gz
    exclude_path:
      - "{{ item.stat.path }}/tmp/*"
      - "{{ item.stat.path }}/log/*"
      - "{{ item.stat.path }}/*.tar*"
      - "{{ item.stat.path }}/*.gz"
      - "{{ item.stat.path }}/*.zip"
      - "{{ item.stat.path }}/*.bz2"
      - "*.log"
  when: not item.skipped|d()
  with_items: "{{ vhost_reg_home.results }}"
  loop_control:
    label: "{{ item.item.name }}"
  tags: [ archive ]

- name: remove homedir
  file:
    path: "{{ item.stat.path }}"
    state: absent
  when: not item.skipped|d()
  with_items: "{{ vhost_reg_home.results }}"
  loop_control:
    label: "{{ item.item.name }}"
  ignore_errors: yes
  tags: [ archive ]
...
