---
- name: Initial bitrix webroot content
  shell: >
    cp -ru --preserve=mode /home/bitrix/www/* {{ vhost_basedir }}/{{ item.user|d(item.name) }}/{{ item.webroot|d('www') }}/
    && chown -R {{ item.user|d(item.name) }}:{{ item.user|d(item.name) }}
    {{ vhost_basedir }}/{{ item.user|d(item.name) }}/{{ item.webroot|d('www') }}
  args:
    creates: "{{ vhost_basedir }}/{{ item.user|d(item.name) }}/{{ item.webroot|d('www') }}/index.php"
  when:
    - item.state|d(true)
    - not item.legacy|d()
    - item.nginx_301_only is not defined
  with_items: "{{ vhost }}"
  loop_control:
    label: "{{ item.user|d(item.name) }}"

- name: Check umask in dbconn.php
  lineinfile:
    path: "{{ vhost_basedir }}/{{ item[1].user|d(item[1].name) }}/{{ item[1].webroot|d('www') }}/bitrix/php_interface/dbconn.php"
    regexp: 'define.+BX_{{ item[0] }}_PERMISSIONS'
    line: 'define("BX_{{ item[0] }}_PERMISSIONS", {{ (item[0] == "FILE")|ternary("0664", "0775") }});'
    insertbefore: '\?>$'
  when:
    - item[1].state|d(true)
    - item[1].nginx_301_only is not defined
  with_nested:
    - [ 'FILE', 'DIR' ]
    - "{{ vhost }}"
  loop_control:
    label: "{{ item[1].user|d(item[1].name) }}"
  ignore_errors: yes

- name: Bitrix cron task
  cron:
    name: Standard bitrix cron task
    user: "{{ item.user|d(item.name) }}"
    job: >
      test -f
      {{ vhost_basedir }}/{{ item.user|d(item.name) }}/{{ item.webroot|d('www') }}/bitrix/modules/main/tools/cron_events.php
      && { /usr/bin/php -f
      {{ vhost_basedir }}/{{ item.user|d(item.name) }}/{{ item.webroot|d('www') }}/bitrix/modules/main/tools/cron_events.php;
      } >/dev/null 2>&1
    state: "{{ item.state|d(true) | ternary('present','absent') }}"
  when:
    - item.nginx_301_only is not defined
  with_items: "{{ vhost }}"
  loop_control:
    label: "{{ item.user|d(item.name) }}"

- name: "Template user's msmtprc"
  template:
    src: "msmtprc.j2"
    dest: "{{ vhost_basedir }}/{{ item.user|d(item.name) }}/.msmtprc"
    owner: "{{ item.user|d(item.name) }}"
    group: "{{ item.user|d(item.name) }}"
    mode: 0644
  when:
    - item.state|d(true)
    - item.nginx_301_only is not defined
  with_items: "{{ vhost }}"
  loop_control:
    label: "{{ item.user|d(item.name) }}"

- name: Include multisite
  include_tasks: bitrix-multisite.yml
  when:
    - multi[0].state|d(true)
    - multi[0].nginx_301_only is not defined
  with_subelements:
    - "{{ vhost }}"
    - bitrix_multisite
    - flags:
      skip_missing: true
  loop_control:
    loop_var: multi
    label: "{{ multi[0].name }}:{{ multi[1].name }}"

...
