---
- name: copy certificates
  copy:
    src: "{{ inventory_dir }}/../files/crypto/{{ item.idna|d()|ternary(item.name.encode('idna'), item.name) }}.crt"
    dest: "/etc/pki/tls/certs/"
    owner: root
    group: root
    mode: 0644
  when:
    - item.crypto|d('none') != 'none'
    - not item.crypto_le|d()
    - not item.legacy|d()
    - not item.crypto_wildcard|d()
  loop: "{{ vhost|rejectattr('state', 'sameas', false)|list }}"
  loop_control:
    label: "{{ item.name }}"
  notify: validate nginx
  tags: [ crypto ]

- name: copy keys
  copy:
    src: "{{ inventory_dir }}/../files/crypto/{{ item.idna|d()|ternary(item.name.encode('idna'), item.name) }}.key"
    dest: "/etc/pki/tls/private/"
    owner: root
    group: root
    mode: 0400
  when:
    - item.crypto|d('none') != 'none'
    - not item.crypto_le|d()
    - not item.legacy|d()
    - not item.crypto_wildcard|d()
  loop: "{{ vhost|rejectattr('state', 'sameas', false)|list }}"
  loop_control:
    label: "{{ item.name }}"
  notify: validate nginx
  tags: [ crypto ]

- name: copy mobile certificates
  copy:
    src: "{{ inventory_dir }}/../files/crypto/m.{{ item.name }}.crt"
    dest: "/etc/pki/tls/certs/"
    owner: root
    group: root
    mode: 0644
  when:
    - item.crypto_mobile|d(item.crypto|d('none')) != 'none'
    - not item.crypto_le|d()
    - item.mobile|d()
    - not item.legacy|d()
    - not item.crypto_wildcard|d()
  loop: "{{ vhost|rejectattr('state', 'sameas', false)|list }}"
  loop_control:
    label: "{{ item.name }}"
  notify: validate nginx
  tags: [ crypto ]

- name: copy mobile keys
  copy:
    src: "{{ inventory_dir }}/../files/crypto/m.{{ item.name }}.key"
    dest: "/etc/pki/tls/private/"
    owner: root
    group: root
    mode: 0400
  when:
    - item.crypto_mobile|d(item.crypto|d('none')) != 'none'
    - not item.crypto_le|d()
    - item.mobile|d()
    - not item.legacy|d()
    - not item.crypto_wildcard|d()
  loop: "{{ vhost|rejectattr('state', 'sameas', false)|list }}"
  loop_control:
    label: "{{ item.name }}"
  notify: validate nginx
  tags: [ crypto ]

- name: copy wildcard certificates
  copy:
    src: "{{ inventory_dir }}/../files/crypto/{{ item.name|regex_replace('^(.*\\.)?([-a-zA-Z0-9]+\\.[a-zA-Z]+)$', '_\\2') }}.crt"
    dest: "/etc/pki/tls/certs/"
    owner: root
    group: root
    mode: 0644
  when:
    - item.crypto|d('none') != 'none'
    - not item.crypto_le|d()
    - not item.legacy|d()
    - item.crypto_wildcard|d()
  loop: "{{ vhost|rejectattr('state', 'sameas', false)|list }}"
  loop_control:
    label: "{{ item.name }}"
  notify: validate nginx
  tags: [ crypto ]

- name: copy wildcard keys
  copy:
    src: "{{ inventory_dir }}/../files/crypto/{{ item.name|regex_replace('^(.*\\.)?([-a-zA-Z0-9]+\\.[a-zA-Z]+)$', '_\\2') }}.key"
    dest: "/etc/pki/tls/private/"
    owner: root
    group: root
    mode: 0400
  when:
    - item.crypto|d('none') != 'none'
    - not item.crypto_le|d()
    - not item.legacy|d()
    - item.crypto_wildcard|d()
  loop: "{{ vhost|rejectattr('state', 'sameas', false)|list }}"
  loop_control:
    label: "{{ item.name }}"
  notify: validate nginx
  tags: [ crypto ]
...
