---
- name: ddns update
  nsupdate:
    server: "{{ vhost_ddns_server }}"
    zone: "{{ item.ddns.zone|d(vhost_default_ddns_zone) }}"
    record: "{{ item.ddns.record|d(item.name|regex_replace('.' ~ vhost_default_ddns_zone ~ '$', '')) }}"
    type: "{{ item.ddns.type|d('CNAME') }}"
    value: "{{ item.ddns.value|d(ansible_fqdn ~ '.') }}"
    state: "{{ item.state|d(true)|ternary('present', 'absent') }}"
    key_name: "{{ vhost_ddns_key_name|d('ddns_key') }}"
    key_algorithm: "{{ vhost_ddns_key_algorithm|d('hmac-md5') }}"
    key_secret: "{{ vhost_ddns_key_secret }}"
  when:
    - item.ddns is defined
    - item.ddns.enable|d()
  with_items: "{{ vhost }}"
  loop_control:
    label: "{{ item.name }}"
  tags: [ ddns ]

- name: ddns update mobile
  nsupdate:
    server: "{{ vhost_ddns_server }}"
    zone: "{{ item.ddns.zone|d(vhost_default_ddns_zone) }}"
    record: "m.{{ item.ddns.record|d(item.name|regex_replace('.' ~ vhost_default_ddns_zone ~ '$', '')) }}"
    type: "{{ item.ddns.type|d('CNAME') }}"
    value: "{{ item.ddns.value|d(ansible_fqdn ~ '.') }}"
    state: "{{ item.state|d(true)|ternary('present', 'absent') }}"
    key_name: "{{ vhost_ddns_key_name|d('ddns_key') }}"
    key_algorithm: "{{ vhost_ddns_key_algorithm|d('hmac-md5') }}"
    key_secret: "{{ vhost_ddns_key_secret }}"
  when:
    - item.ddns is defined
    - item.ddns.enable|d()
    - item.mobile|d()
  with_items: "{{ vhost }}"
  loop_control:
    label: "{{ item.name }}"
  tags: [ ddns ]
...
