---
- name: Block in /etc/hosts
  blockinfile:
    path: "/etc/hosts"
    marker: '# ANSIBLE MANAGED {{ item.name|upper }} {mark}'
    block: |
      {% if item.listen is defined %}
      {{ item.listen[0].ipaddr }} {{ item.name }}
      {% else %}
      vhost_default_ipaddr {{ item.name }}
      {% endif %}
    state: "{{ item.hosts|d()|ternary('present','absent') }}"
  with_items: "{{ vhost }}"
  loop_control:
    label: "{{ item.name }}"
...
