---
- name: Disable Laravel instantiated units
  systemd:
    name: "{{ item[1].name|d('laravel-queue-worker') }}@{{ item[0].user|d(item[0].name) }}"
    state: stopped
    enabled: no
  when: not item[0].state|d(True)
  loop: "{{ vhost|subelements('php_laravel_units', skip_missing=True) }}"
  loop_control:
    label: "{{ item[1].name|d('laravel-queue-worker') }}@{{ item[0].user|d(item[0].name) }}"

...
