---
- name: Import init
  import_tasks: init.yml

- name: Include bitrix-pre
  include_tasks: bitrix-pre.yml
  when: vhost_backend == 'bitrix'

- name: Include user
  include_tasks: user.yml
  when: vhost_backend != 'reverse-proxy'
  tags: [ user, password, db, redmine ]

- name: Bitrix section
  block:
    - name: Include bitrix
      include_tasks: bitrix.yml
      tags: [ crypto ]

    - name: Include hosts
      include_tasks: hosts.yml
      tags: [ hosts ]
  when: vhost_backend == 'bitrix'

- name: Ordinary section
  block:
    - name: Include wiki
      include_tasks: wiki.yml
      tags: [ wiki ]

    - name: Include archive
      include_tasks: archive.yml
  when: vhost_backend != 'reverse-proxy'

- name: Import crypto
  import_tasks: crypto.yml

- name: Bitrix section
  block:
    - name: Include nginx
      include_tasks: nginx.yml

    - name: Include nginx-bx
      include_tasks: nginx-bx.yml
  when: vhost_backend == 'bitrix'
  tags: [ crypto ]

- name: Include apache
  include_tasks: apache.yml
  when: >
    vhost_backend == 'apache'
    or vhost_backend == 'bitrix'

- name: Include laravel
  include_tasks: laravel.yml
  when: vhost_backend == 'php-fpm'

- name: Ordinary section
  block:
    - name: Include ddns
      include_tasks: ddns.yml
      tags: [ ddns ]

    - name: Include mysql
      include_tasks: mysql.yml

    - name: Include postgresql
      include_tasks: postgresql.yml

    - name: Flush handlers
      meta: flush_handlers

    - name: Include gitlab
      include_tasks: gitlab.yml
      tags: [ gitlab ]

    - name: Include redmine
      include_tasks: redmine.yml
      tags: [ user, redmine ]

    - name: Include repo
      include_tasks: repo.yml
      tags: [ repo ]
  when: vhost_backend != 'reverse-proxy'

- name: Import webcheck
  import_tasks: webcheck.yml

- name: Include wiki_print (tail)
  include_tasks: wiki_print.yml
  when: vhost_backend != 'reverse-proxy'
  tags: [ wiki ]
...
