---
- name: Attempt to dump mysql database
  block:
    - name: dump mysql database
      mysql_db:
        name: "{{ item[0].db.name }}"
        state: dump
        target: "{{ vhost_preserve }}/{{ item[0].db.name }}-{{ vhost_timestamp }}.sql.bz2"
        login_host: "{{ item[0].db.host }}"
        login_port: "{{ item[0].db.port|d('3306') }}"
        login_user: "{{ vhost_db_mysql_admin_user }}"
        login_password: "{{ vhost_db_mysql_admin_pass }}"
      register: vhost_dump_mysql_result
      when:
        - item[0].db is defined
        - item[0].db.type == 'mysql'
        - item[1].changed
        - item[1].state == 'absent'
      failed_when:
        - vhost_dump_mysql_result.failed
        - "'Cannot dump database ' ~ item[0].db.name ~ ' - not found' not in vhost_dump_mysql_result.msg"
      loop: "{{ vhost|zip(vhost_user.results)|list }}"
      loop_control:
        label: "{{ item[0].name }}"
      tags: [ db ]
  rescue:
    - name: Create user back if dump error
      user:
        name: "{{ item[0].user|d(item[0].name) }}"
        create_home: no
        state: present
      when:
        - item[0].db is defined
        - item[0].db.type == 'mysql'
        - item[1].state == 'absent'
        - item[1].changed
      loop: "{{ vhost|zip(vhost_user.results)|list }}"
      loop_control:
        label: "{{ item[0].user|d(item[0].name) }}"
      tags: [ db ]

    - name: Exit
      fail:
        msg: "MYSQL DUMP ERROR"
      tags: [ db ]

- name: manage mysql database
  mysql_db:
    name: "{{ item.db.name }}"
    state: "{{ item.state|d(true)|ternary('present', 'absent') }}"
    encoding: "{{ item.db.encoding|d('utf8') }}"
    collation: "{{ item.db.collation|d('utf8_general_ci') }}"
    login_host: "{{ item.db.host }}"
    login_port: "{{ item.db.port|d('3306') }}"
    login_user: "{{ vhost_db_mysql_admin_user }}"
    login_password: "{{ vhost_db_mysql_admin_pass }}"
  when: item.db.type == 'mysql'
  loop: "{{ vhost|selectattr('db', 'defined')|list }}"
  loop_control:
    label: "{{ item.name }}"
  tags: [ db ]

- name: manage mysql user
  mysql_user:
    name: "{{ item.db.name }}"
    password: "{{ item.db.pass }}"
    host: "%"
    priv: "{{ item.db.name }}.*:ALL"
    state: "{{ item.state|d(true)|ternary('present', 'absent') }}"
    login_host: "{{ item.db.host }}"
    login_port: "{{ item.db.port|d('3306') }}"
    login_user: "{{ vhost_db_mysql_admin_user }}"
    login_password: "{{ vhost_db_mysql_admin_pass }}"
  when: item.db.type == 'mysql'
  loop: "{{ vhost|selectattr('db', 'defined')|list }}"
  loop_control:
    label: "{{ item.name }}"
  tags: [ db ]
...
