---
- name: template nginx vhost config
  template:
    src: "nginx.j2"
    dest: "/etc/nginx/conf.d/{{ item.name }}.conf"
    mode: 0644
    backup: yes
  when: item.state|d(true)
  with_items: "{{ vhost }}"
  loop_control:
    label: "{{ item.name }}"
  notify: validate nginx
  tags: [ conf ]

- name: remove nginx vhost config
  file:
    path: "/etc/nginx/conf.d/{{ item.name }}.conf"
    state: absent
    backup: yes
  when: not item.state|d(true)
  with_items: "{{ vhost }}"
  loop_control:
    label: "{{ item.name }}"
  notify: validate nginx
  tags: [ conf ]

- name: template php-fpm vhost config
  template:
    src: "php-fpm.j2"
    dest: "/etc/php-fpm.d/{{ item.name }}.conf"
    mode: 0644
    backup: yes
  when:
    - vhost_backend == 'php-fpm'
    - item.state|d(true)
  with_items: "{{ vhost }}"
  loop_control:
    label: "{{ item.name }}"
  notify: validate php-fpm
  tags: [ conf ]

- name: remove php-fpm vhost config
  file:
    path: "/etc/php-fpm.d/{{ item.name }}.conf"
    state: absent
    backup: yes
  when:
    - vhost_backend == 'php-fpm'
    - not item.state|d(true)
  with_items: "{{ vhost }}"
  loop_control:
    label: "{{ item.name }}"
  notify: validate php-fpm
  tags: [ conf ]

- name: template apache vhost config
  template:
    src: "apache.j2"
    dest: "/etc/httpd/conf.d/{{ item.name }}.conf"
    mode: 0644
    backup: yes
  when:
    - vhost_backend == 'apache'
    - item.state|d(true)
  with_items: "{{ vhost }}"
  loop_control:
    label: "{{ item.name }}"
  notify: validate apache
  tags: [ conf ]

- name: remove apache vhost config
  file:
    path: "/etc/httpd/conf.d/{{ item.name }}.conf"
    state: absent
    backup: yes
  when:
    - vhost_backend == 'apache'
    - not item.state|d(true)
  with_items: "{{ vhost }}"
  loop_control:
    label: "{{ item.name }}"
  notify: validate apache
  tags: [ conf ]
...
