---
- name: "Template Nginx vhost config (Bitrix: site_available)"
  template:
    src: "nginx-bx.j2"
    dest: "/etc/nginx/bx/site_avaliable/{{ op.user|d(op.name) }}.conf"
    mode: 0644
    backup: yes
    force: "{{ op.legacy|d()|ternary('no', 'yes') }}"
  loop: "{{ vhost }}"
  loop_control:
    loop_var: op
    label: "{{ op.name }}"
  register: vhost_bx_nginx_conf
  notify: validate nginx
  tags: [ conf, crypto ]

- name: "Manage symlink Nginx vhost config (Bitrix: site_enabled)"
  file:
    path: "/etc/nginx/bx/site_enabled/{{ item[1].dest|basename }}"
    src: "{{ item[0].state|d(True)|ternary('../site_avaliable/' ~ item[1].dest|basename, omit) }}"
    state: "{{ item[0].state|d(True)|ternary('link', 'absent') }}"
  loop: "{{ vhost|zip(vhost_bx_nginx_conf.results)|list }}"
  loop_control:
    label: "{{ item[1].dest|d('null')|basename }}"
  notify: validate nginx
  tags: [ conf, crypto ]

...
