---
- name: Template php-fpm vhost config
  template:
    src: "php-fpm.j2"
    dest: "/etc/php-fpm.d/{{ item.user|d(item.name) }}.conf"
    mode: 0644
    backup: yes
    force: "{{ item.legacy|d()|ternary('no', 'yes') }}"
  when:
    - item.state|d(True)
    - item.nginx_301_only is not defined
    - item.fpm is defined
  loop: "{{ vhost }}"
  loop_control:
    label: "{{ item.name }}"
  notify: validate php-fpm
  tags: [ conf ]

- name: Remove php-fpm vhost config
  file:
    path: "/etc/php-fpm.d/{{ item.user|d(item.name) }}.conf"
    state: absent
    backup: yes
  when:
    - not item.state|d(True)
    - item.nginx_301_only is not defined
    - item.fpm is defined
  loop: "{{ vhost }}"
  loop_control:
    label: "{{ item.name }}"
  notify: validate php-fpm
  tags: [ conf ]
...
