---
- name: create redmine project
  become: yes
  become_user: apache
  shell: >
      script/rails runner -e production
      "Project.create :name => '{{ item.redmine.title | d(item.name
      | regex_replace('.' ~ vhost_default_ddns_zone ~ '$', '')) }}',
      :description => '{{ item.redmine.description }}{% if item.repo is defined %}Репозиторий:
      %{color:ForestGreen}@{{ vhost_git_server }}:{{ vhost_git_path }}/{{ (item.repo
      | default(dict(name=item.name | regex_replace('.' ~ vhost_default_ddns_zone ~ '$', ''))))['name']
      | d(item.name | regex_replace('.' ~ vhost_default_ddns_zone ~ '$', '')) }}@%{% endif %}',
      :identifier => '{{ item.redmine.id | d(item.name
      | regex_replace('.' ~ vhost_default_ddns_zone ~ '$', '') | regex_replace('\.', '-')) }}',
      :is_public=>'0', :homepage=>'http://{{ item.name | regex_replace('.' ~ vhost_default_ddns_zone ~ '$', '') }}',
      :enabled_module_names=>['wiki', '{{ (vhost_backend == 'bitrix' ) | ternary('','repository') }}']" &&
      touch "creates/{{ item.name | regex_replace('.' ~ vhost_default_ddns_zone ~ '$', '') }}"
  args:
    chdir: "/var/www/redmine"
    creates: "creates/{{ item.name | regex_replace('.' ~ vhost_default_ddns_zone ~ '$', '') }}"
  delegate_to: "{{ vhost_redmine_server }}"
  loop: "{{ vhost|selectattr('redmine', 'defined')|list }}"
  loop_control:
    label: "{{ item.name }}"
  ignore_errors: yes
  tags: [ user, redmine ]
...
