---
- name: print a path to the wiki file
  debug:
    msg: >
      Wiki content /tmp/vhost_{{ item[0].name }}.txt
  when:
    - item[1].changed
    - item[1].state == 'present'
  with_together:
    - "{{ vhost }}"
    - "{{ vhost_user.results }}"
  loop_control:
    label: "{{ item[0].name }}"
  tags: [ wiki ]
...
