---
- name: Directories for pcmk stuff
  file:
    path: "/{{ item.path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - path: "{{ redis_pcmk_ra_dir }}/{{ redis_pcmk_ra_org }}"
    - path: "{{ redis_pcmk_scripts_dir }}"

- name: Copy custom resource agent redis
  copy:
    src: "{{ item.path }}"
    dest: "/{{ item.path|dirname }}/{{ redis_pcmk_ra_org }}/{{ item.path|basename }}"
    owner: root
    group: root
    mode: 0755
  loop:
    - path: "{{ redis_pcmk_ra_dir }}/redis"

- name: Template pcs init script
  template:
    src: "{{ item.path }}.j2"
    dest: "/{{ item.path }}"
    owner: root
    group: root
    mode: 0755
  loop:
    - path: "{{ redis_pcmk_scripts_dir }}/redis.pcs"

- name: Get flag file stat
  stat:
    path: "{{ redis_pcmk_flag }}"
  register: redis_reg_pcmk

- name: Execute pcs script
  command: >
    /{{ redis_pcmk_scripts_dir }}/redis.pcs
  when:
    - inventory_hostname == groups[pcmk_pool]|first
    - not redis_reg_pcmk.stat.exists

- name: Touch lock
  copy:
    dest: "{{ redis_pcmk_flag }}"
    content: >
      # REDIS PCMK CLUSTER CREATED
    mode: 0400
...
