---
- name: reload httpd
  systemd:
    name: httpd.service
    state: reloaded
  when: "'httpd' in roles"

- name: reload php-fpm
  systemd:
    name: php-fpm.service
    state: reloaded
  when: "'php-fpm' in roles"
...
