---
- name: reload httpd
  systemd:
    name: httpd.service
    state: reloaded
  listen: reload php
  when: inventory_hostname in groups['httpd']

- name: reload php-fpm
  systemd:
    name: php-fpm.service
    state: reloaded
  listen: reload php
  when: inventory_hostname in groups['php_fpm']
...
