---
- name: reload httpd
  systemd:
    name: httpd.service
    state: reloaded
  listen: reload php
  when: >
    'httpd' in server_roles

- name: reload php-fpm
  systemd:
    name: php-fpm.service
    state: reloaded
  listen: reload php
  when: >
    'php-fpm' in server_roles
...
