---
- name: units section
  block:
    - name: Template Laravel instantiated units
      template:
        src: "systemd/laravel-queue.j2"
        dest: "/etc/systemd/system/{{ item.name|d('laravel-queue-worker') }}@.service"
        owner: root
        group: root
        mode: 0644
      loop: "{{ php_laravel_units|rejectattr('state', 'sameas', false)|list }}"
      notify: systemd reload

    - name: Remove Laravel instantiated units
      file:
        path: "/etc/systemd/system/{{ item.name|d('laravel-queue-worker') }}@.service"
        state: absent
      loop: "{{ php_laravel_units|selectattr('state', 'sameas', false)|list }}"
      notify: systemd reload
  when: php_laravel_units|length > 0
...
