---
- name: Check if role assigned to host
  assert:
    that:
      - inventory_hostname in groups['php_fpm']

- import_tasks: packages.yml

- name: "Copy index.php"
  copy:
    dest: /var/www
    src: index.php
    force: yes
  tags: [ index ]

# UMASK
- name: "Set umask for php-fpm service"
  blockinfile:
    dest: /etc/systemd/system/php-fpm.service.d/php-fpm.conf
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK: UMASK"
    block: |
      [Service]
      UMask=0002
  notify: config restart php-fpm
  tags: [ services ]

- name: Set ini ondemand for default pool
  ini_file:
    path: "/etc/php-fpm.d/www.conf"
    section: www
    option: pm
    value: ondemand
  notify: config reload php-fpm

- name: Service enabled and started
  systemd:
    name: php-fpm.service
    state: started
    enabled: yes

- name: Include laravel
  include_tasks: laravel.yml

- name: Include logrotate
  include_tasks: logrotate.yml

- name: Include awstats
  include_tasks: awstats.yml
...
