---
- name: Check if role assigned to host
  assert:
    that:
      - inventory_hostname in groups['unit']

- name: Include packages
  include_tasks: packages.yml

- name: Enable unit service
  service:
    name: unit
    enabled: yes
    state: started
...
