---
- name: Check VMs
  virt:
    command: list_vms
  register: kvm_existing_vms

- name: Determine host CPU model
  shell: >
    virsh capabilities
    | awk '/model/ { gsub(/<\/*[[:alnum:]]*>/, ""); gsub(/[[:space:]]/, ""); print; exit }'
  register: kvm_host_cpu_model
  changed_when: false

# Extract pool 'path' and 'pool type' fields from pool XML-file,
# located in the /etc/libvirt/storage, and store these values in
# the kvm_pool_result.results.stdout_lines
- name: Determine pool path
  shell: >
    awk '/path/ { gsub(/<\/*[[:alnum:]]*>/, ""); gsub(/[[:space:]]/, ""); path=$0 };
    /pool type/ { match($0, /dir|logical/); type=substr($0, RSTART, RLENGTH) };
    END { print path; print type }' /etc/libvirt/storage/{{ item.pool_name }}.xml
  when: item.name not in kvm_existing_vms.list_vms
  with_items: "{{ kvm_vm }}"
  loop_control:
    label: "{{ item.pool_name }}"
  register: kvm_pool_result
  changed_when: kvm_pool_result.stdout_lines is defined

- name: Include main VM tasks
  include_tasks: vm.yml
  when:
    - kvm_pool_result.results is defined
    - kvm_pool_result.changed

- name: Include VM state tasks
  import_tasks: vm_state.yml
...
