---
- name: Check VM state
  virt:
    name: "{{ item.name }}"
    state: "{{ item.state|d('running') }}"
  when: item.state|d('running') != 'undefined'
  with_items: "{{ kvm_vm }}"
  loop_control:
    label: "{{ item.name }}:{{ item.state|d('running') }}"

- name: Manage VM autostart
  virt:
    name: "{{ item.name }}"
    autostart: "{{ (item.state|d('running') == 'running')|ternary('true','false') }}"
  when: item.state|d('running') != 'undefined'
  with_items: "{{ kvm_vm }}"
  loop_control:
    label: "{{ item.name }}:{{ (item.state|d('running') == 'running')|ternary('true','false') }}"
  failed_when: false
...
