---
- name: Check VM state
  virt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  when:
    - item.state is defined
  with_items: "{{ kvm_vm }}"
  loop_control:
    label: "{{ item.name }}:{{ item.state|d('null') }}"

- name: Manage VM autostart
  virt:
    name: "{{ item.name }}"
    autostart: "{{ (item.state == "running")|ternary('true','false') }}"
  when:
    - item.state is defined
  with_items: "{{ kvm_vm }}"
  loop_control:
    label: "{{ item.name }}:{{ (item.state|d('null') == "running")|ternary('true','false') }}"
  failed_when: false
...
