---
- name: Check role requirements
  assert:
    that:
      - inventory_hostname in groups['nodejs'] or inventory_hostname in groups['build_runners'] or inventory_hostname in groups['unit']
      - ansible_distribution_file_variety == "RedHat"
      - ansible_distribution_major_version|int >= 7

- name: Install nodejs repo
  yum:
    name: >
      https://rpm.nodesource.com/pub_{{ nodejs_major_version
      }}.x/el/{{ ansible_distribution_major_version }}/{{ ansible_architecture
      }}/nodesource-release-el{{ ansible_distribution_major_version }}-1.noarch.rpm

- name: Yum install nodejs
  yum:
    name: nodejs

- name: Yarn section
  block:
    - name: Ensure yarn repository key is present
      rpm_key:
        key: "https://dl.yarnpkg.com/rpm/pubkey.gpg"

    - name: Create yarn repo
      yum_repository:
        name: yarn
        description: Yarn Repository
        file: yarn
        baseurl: https://dl.yarnpkg.com/rpm/
        enabled: yes
        gpgcheck: yes
        gpgkey: https://dl.yarnpkg.com/rpm/pubkey.gpg

    - name: Yum install yarn
      yum:
        name: yarn
  when: nodejs_yarn_install|d()

- name: nuxt section
  block:
    - name: Copy nuxt.js instantiated unit
      copy:
        src: "etc/systemd/system/node-nuxt-frontend.service"
        dest: /etc/systemd/system/node-nuxt-frontend@.service
        owner: root
        group: root
        mode: "0644"
      notify: systemd reload

    - name: Create nuxt conf dir
      file:
        path: /usr/local/etc/nuxt
        state: directory
        mode: "0755"
  when: nodejs_nuxt_service

- name: Remove nuxt.js instantiated unit
  file:
    path: /etc/systemd/system/node-nuxt-frontend@.service
    state: absent
  when: not nodejs_nuxt_service
  notify: systemd reload

- meta: flush_handlers
...
