---
- name: package scl installed
  command: "yum-config-manager --enable rhel-server-rhscl-7-rpms"

- name: service icinga2 restart
  systemd:
    name: icinga2.service
    state: restarted

- name: service icinga2 reload
  systemd:
    name: icinga2.service
    state: reloaded

- name: pip installed
  command: "pip3 install dnspython sleekxmpp"

- name: restart authd
  systemd:
    name: "auth.socket"
    state: restarted
    daemon_reload: yes
...
