---
- name: Check role requirements
  assert:
    that:
      - ansible_distribution_file_variety == 'RedHat'
      - ansible_distribution_major_version|int == 7
      - bridge_devices|length > 0

- name: Sanity check (I)
  fail:
    msg: "{{ item.address }} is not ipv4 address"
  when:
    - item.address is defined
    - not item.address|ipv4
  with_items: "{{ bridge_devices }}"
  loop_control:
    label: "{{ item.address|d('null') }} ipv4 test"

- name: Sanity check (II)
  fail:
    msg: "{{ item.peer }} is not ipv4 address"
  when:
    - item.peer is defined
    - not item.peer|ipv4
  with_items: "{{ bridge_devices }}"
  loop_control:
    label: "{{ item.peer|d('null') }} ipv4 test"

- name: Presence of required packages
  yum:
    name: "{{ bridge_pkgs }}"
    state: present

- include: nonm.yml

- include: configure.yml

- name: Unwanted files is absent
  file:
    path: "{{ bridge_ifcfg_path }}/{{ item }}"
    state: absent
  with_items: "{{ bridge_unwanted_files }}"

- include: ifcfg.yml
...
