---
- name: Check if NetworkManager is installed
  stat:
    path: "/usr/lib/systemd/system/NetworkManager.service"
  register: bridge_check_nm
  when: ansible_distribution_major_version|int >= 7

- name: NetworkManager service disabled
  systemd:
    name: NetworkManager
    state: stopped
    enabled: no
  when:
    - ansible_distribution_major_version|int >= 7
    - bridge_check_nm.stat.exists

- name: Oldschool network service started
  service:
    name: network
    state: started
    enabled: yes
...
