---
- name: Dir git system-wide hooks
  file:
    path: /etc/git/hooks
    state: directory
    mode: 0755
  tags: [ git ]

- name: System Git config core.hooksPath  # noqa 303
  shell: >
    git config --system core.hooksPath /etc/git/hooks
    && touch {{ flags_dir }}/git.core.hooksPath
  args:
    creates: "{{ flags_dir }}/git.core.hooksPath"
  tags: [ git ]

- name: Template Git post-checkout and post-merge hooks
  template:
    src: "etc/git/hooks/git-selinux-hook.j2"
    dest: "/etc/git/hooks/{{ item }}"
    mode: 0775
    backup: yes
  loop:
    - post-checkout
    - post-merge
  loop_control:
    label: "{{ item }}"
  tags: [ git ]
...
