---
- name: restart bacula-fd
  service:
    name: bacula-fd
    state: restarted

- name: validate bacula-dir
  command: >
    bacula-dir -t
  delegate_to: "{{ bacula_dir.host }}"
  notify: reload bacula-dir

- name: reload bacula-dir
  shell: >
    echo reload | bconsole
  delegate_to: "{{ bacula_dir.host }}"
  notify: check bacula-dir

- name: check bacula-dir
  service:
    name: bacula-dir
    state: started
  delegate_to: "{{ bacula_dir.host }}"
...
